---
title: "Appendix (Extra analyses)"
author: "Connor Quiroz"
date: "2025-02-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# General data cleaning + visualization + analysis packages
library(tidyverse)
library(ggformula)
library(countrycode)
library(data.table)
library(arrow)
library(cowplot)
library(RColorBrewer)

# Map creation
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)

# Load in packages needed for ARTIS
library(devtools)
library(tidytext)
# devtools::install_github("davidsjoberg/ggsankey")
library(ggsankey)
# devtools::install_github("Seafood-Globalization-Lab/exploreARTIS@v1.0.0", dependencies = TRUE)
library(exploreARTIS)

# For Packages for fishbase
# remotes::install_github("cboettig/duckdbfs", force = TRUE)
# remotes::install_github("ropensci/rfishbase")
library(duckdbfs)
library(rfishbase)
```

```{r load in functions}
# Function description
# grouping: Define which variable you want to group by
# taxa_var: input the name of the taxa variable you want to search for (e.g., "taxa_var = sciname_hs_modified" will run operations on that variable)
at_least_vars <- function(data = con_joined, grouping = "producer_iso3c", taxa_var = "sciname") {
  if (any(names(data) %in% grouping)) {
    new_data <- data %>%
      group_by(!!sym(grouping), !!sym(taxa_var)) %>%
      mutate(
        at_least_species = case_when(
          taxa_level == "species" ~ 1, TRUE ~ 0),
        at_least_genus = case_when(
          taxa_level == "species" |
          taxa_level == "genus" ~ 1, TRUE ~ 0),
        at_least_family = case_when(
          taxa_level == "species" |
          taxa_level == "genus" |
          taxa_level == "family" ~ 1,
          TRUE ~ 0
        ),
        at_least_order = case_when(
          taxa_level == "species" |
            taxa_level == "genus" |
            taxa_level == "family" |
            taxa_level == "order" ~ 1,
          TRUE ~ 0
        ),
        at_least_class = case_when(
          taxa_level == "species" |
            taxa_level == "genus" |
            taxa_level == "family" |
            taxa_level == "order" | 
            taxa_level == "class" ~ 1,
          TRUE ~ 0
        ),
        at_least_phylum = case_when(
          taxa_level == "species" |
            taxa_level == "genus" |
            taxa_level == "family" |
            taxa_level == "order" | 
            taxa_level == "class" |
            taxa_level == "phylum" ~ 1,
          TRUE ~ 0
        ),
        at_least_kingdom = case_when(
          taxa_level == "species" |
            taxa_level == "genus" |
            taxa_level == "family" |
            taxa_level == "order" | 
            taxa_level == "class" |
            taxa_level == "phylum" |
            taxa_level == "kingdom" ~ 1,
          TRUE ~ 0
        )
      )
  }
  else {
    new_data <- data %>%
      group_by(!!sym(taxa_var)) %>%
      mutate(
        at_least_species = case_when(taxa_level == "species" ~ 1, TRUE ~ 0),
        at_least_genus = case_when(taxa_level == "species" |
                                     taxa_level == "genus" ~ 1, TRUE ~ 0),
        at_least_family = case_when(
          taxa_level == "species" |
            taxa_level == "genus" | taxa_level == "family" ~ 1,
          TRUE ~ 0
        ),
        at_least_order = case_when(
          taxa_level == "species" |
            taxa_level == "genus" |
            taxa_level == "family" | taxa_level == "order" ~ 1,
          TRUE ~ 0
        ),
        at_least_class = case_when(
          taxa_level == "species" |
            taxa_level == "genus" |
            taxa_level == "family" |
            taxa_level == "order" | 
            taxa_level == "class" ~ 1,
          TRUE ~ 0
        )
      )
  }
  
  # Copy input data to use throughout loop
  data_1 <- data
  # Calculate proportions for which a country reports to X taxa level
  for (i in c("species", "genus", "family", "order", "class", "phylum", "kingdom")) {
  con_prop_group <- new_data %>%
    group_by(!!sym(grouping)) %>%
    summarize(!!paste0("prop_at_least_", i) := sum(!!sym(paste0("at_least_",i))) / n()) %>%
    ungroup()
  
  # Join prop of each phylogenetic group to already joined consumption dataset
  data_1 <- data_1 %>%
      left_join(con_prop_group, by = grouping)

  }
  return(data_1)
}

taxa_level_vars <- function(data, taxa_var = "sciname",ungroup = FALSE) {
  if (ungroup == FALSE) {
    data %>%
      mutate(
        taxa_level = case_when(
          !!sym(taxa_var) == kingdom ~ "kingdom",
          !!sym(taxa_var) == phylum ~ "phylum",
          !!sym(taxa_var) == superclass ~ "superclass",
          !!sym(taxa_var) == class ~ "class",
          !!sym(taxa_var) == order ~ "order",
          !!sym(taxa_var) == family ~ "family",
          !!sym(taxa_var) == subfamily ~ "subfamily",
          !!sym(taxa_var) == genus ~ "genus",
          str_detect(!!sym(taxa_var), pattern = "\ ") ~ "species"
        )
      )
  }
  
  else {
    data %>%
      ungroup() %>%
      distinct(sciname) %>%
      left_join(sciname, by = "sciname") %>%
      mutate(
        taxa_level = case_when(
          !!sym(taxa_var) == kingdom ~ "kingdom",
          !!sym(taxa_var) == phylum ~ "phylum",
          !!sym(taxa_var) == superclass ~ "superclass",
          !!sym(taxa_var) == class ~ "class",
          !!sym(taxa_var) == order ~ "order",
          !!sym(taxa_var) == family ~ "family",
          !!sym(taxa_var) == subfamily ~ "subfamily",
          !!sym(taxa_var) == genus ~ "genus",
          str_detect(!!sym(taxa_var), pattern = "\ ") ~ "species"
        )
      )
  }
  
  
}

# METHOD 1: FAOAREAS
taxa_presence_or_absence_faoareas <- function(data = "fishbase", obtain_stats = FALSE) {
  # Determine whether to use FB or SLB data
  if (data == "fishbase") {
    artis_fishbase_locations <- fb_presences_faoareas
    species_codes <- fb_species_codes
  }
  else {
    artis_fishbase_locations <- slb_presences_faoareas
    species_codes <- slb_species_codes
  }
  
  # Join species codes to species / genus names
  artis_fishbase_locations <- left_join(artis_fishbase_locations, species_codes[, c("SpecCode", "Genus", "Species")], by = "SpecCode")
  # Identify what eez species distrubutions are in (with faoareas)
  eez_assignments <- data.frame(eez_name = 1:nrow(artis_fishbase_locations))
  
  # Initialize list
  country_list <- list()
  
  # Set length of list
  length(country_list) <- nrow(artis_fishbase_locations)
  
  # METHOD 1: rfishbase::faoareas()
  
  # Assign a country into the present countries if a species distribution intersects with a country's EEZ
  for (i in 1:nrow(artis_fishbase_locations)) {
    for (j in 1:nrow(eez_extents)) {
      lat_check <- (abs(artis_fishbase_locations$SouthernLatitude[i]) <= abs(eez_extents$y_max[j])) &
        (abs(artis_fishbase_locations$NorthernLatitude[i]) >= abs(eez_extents$y_min[j]))
      
      long_check <- (abs(artis_fishbase_locations$WesternLongitude[i]) <= abs(eez_extents$x_max[j])) &
        (abs(artis_fishbase_locations$EasternLongitude[i]) >= abs(eez_extents$x_min[j]))
      if (lat_check & long_check) {
        country_list[[i]] <- c(country_list[[i]], eez_extents$ISO_TER1[j])
        
      }
      if (j == nrow(eez_extents)) {
        if (is.null(country_list[[i]])) {
          country_list[[i]] <- NA
          eez_assignments$eez_name[i] = country_list[[i]]
        }
        else {
          eez_assignments$eez_name[i] = paste0(c(country_list[[i]]), collapse = " ")
        }
      }
    }
  }
  
  # Number of unique country combinations
  length(unique(eez_assignments$eez_name))
  
  # Number of N/S/E/W combinations (make sure it roughly matches with number of unique combinations.)
  artis_fishbase_locations %>%
    distinct(
      NorthernLatitude,
      SouthernLatitude,
      EasternLongitude,
      EasternLongitude,
      WesternLongitude
    )
  
  # Country coverage using FAO distribution data: 154 countries (less than when using country() data.
  length(unique(unlist(country_list)))
  
  # Combine fishbase fishbase location data with their respective countries they're found in
  artis_fishbase_locations_faoareas <- cbind(artis_fishbase_locations, eez_assignments)
  
  # Number of species covered in fishbase via faoareas() - 782 species
  length(unique(artis_fishbase_locations_faoareas[!is.na(artis_fishbase_locations_faoareas$eez_name), ]$Species))
  
  artis_fishbase_locations_faoareas <- artis_fishbase_locations_faoareas %>%
    select(eez_name, Species) %>%
    rename(sciname_joinable_to_fishbase = "Species",
           countries_found = "eez_name")
  
  artis_fishbase_locations_faoareas <- artis_fishbase_locations_faoareas %>%
    distinct(sciname_joinable_to_fishbase, .keep_all = TRUE) %>%
    mutate(source = data)
  
  
  consumption_countries_joined_faoareas <- left_join(consumption_sciname,
                                                     artis_fishbase_locations_faoareas,
                                                     by = "sciname_joinable_to_fishbase")
  #
  # Determine whether a species is present or absent in an EEZ
  consumption_countries_joined_faoareas <- consumption_countries_joined_faoareas %>%
    ungroup() %>%
    mutate(presence_or_absence = case_when(
      str_detect(countries_found, eez_iso3c) ~ 1,
      !str_detect(countries_found, eez_iso3c) ~ 0,
      TRUE ~ NA
    ))
  
  return(consumption_countries_joined_faoareas)
}

# METHOD 2: rfishbase::country()

# Another way to get species distributions in certain countries (need to see how many countries are represented in this vs FAO, which doesn't directly report countries, but needs to be joined on eez data).
taxa_presence_or_absence <- function(data = "fishbase", obtain_stats = FALSE) {
  
  # Determine whether to use FB or SLB data
  if (data == "fishbase") {
    artis_fishbase_locations <- fb_presences_country
    species_codes <- fb_species_codes
  }
  else {
    artis_fishbase_locations <- slb_presences_country
    species_codes <- slb_species_codes
  }
  
  if (obtain_stats == TRUE) {
    # faoareas() and country() have equal coverage - 1075 species from ARTIS' 1326 species
    # 229 countries when dealing with country() data, but how many covered countries when dealing with faoareas() data?
    num_countries <- artis_fishbase_locations %>%
      filter(Status %in% c("native", "Native", "introduced", "endemic") & !is.na(country)) %>%
      mutate(eez_name = countrycode(country, origin = 'country.name', destination = 'iso3c')) %>%
      distinct(eez_name) %>%
      summarize(length = length(eez_name)) %>%
      pull(length)
    print(paste0("Number of countries joined to ", data, ": ", as.character(num_countries)))
    
    # Data coverage:
    num_species_artis <- sum(str_detect(
      unique(scinames_excluding_tradeflows$sciname_joinable_to_fishbase), " "), na.rm = TRUE)
    num_species_fishbase <- artis_fishbase_locations %>%
      summarize(unique_species = length(unique(Species))) %>%
      pull(unique_species)
    
    species_coverage_pct <- round((num_species_fishbase / num_species_artis), 2) * 100
    
    # 81% % coverage of all ARTIS species in fishbase - also try sealifebase?
    print(paste0("Number of species in ", sym(data), ": ", num_species_fishbase))
    print(paste0("Number of species in ARTIS", ": ", num_species_artis))
    print(paste0("Percent of ARTIS species that ", sym(data), " has: ", as.character(species_coverage_pct),"%"))
  }
  else {
    # Which countries species are found in (using country() distribution data)
    fishbase_country_presences <- artis_fishbase_locations %>%
      filter(Status %in% c("native", "Native", "introduced", "endemic")) %>%
      mutate(eez_name = countrycode(country, origin = 'country.name', destination = 'iso3c')) %>%
      group_by(ScientificName) %>%
      summarize(countries_found = paste0(unique(eez_name), collapse = " ")) %>%
      rename(sciname_joinable_to_fishbase = "ScientificName") %>%
      mutate(source = data)
    
    consumption_countries_joined <- left_join(scinames_excluding_tradeflows, fishbase_country_presences, by = "sciname_joinable_to_fishbase")
    
    # # See which entries were successfully joined
    # consumption_countries_joined <- consumption_countries_joined %>%
    #   mutate(
    #     joined = case_when(!is.na(eez_iso3c) & !is.na(countries_found) ~ "both",
    #                        !is.na(eez_iso3c) ~ "only in artis",
    #                        TRUE ~ paste0("only in ", data)),
    #     source = case_when(joined == "both" ~ data,
    #                        joined == paste0("only in ", data) ~ data,
    #                        TRUE ~ NA))

    # Determine whether a species is present or absent in an EEZ
    consumption_countries_joined <- consumption_countries_joined %>%
      ungroup() %>%
      mutate(presence_or_absence = case_when(
        str_detect(countries_found, eez_iso3c) ~ 1, !str_detect(countries_found, eez_iso3c) ~ 0,
        TRUE ~ NA
      ))
    
    return(consumption_countries_joined)
  }
  
  
}
```


```{r}
# CASE STUDY: Look at papua new guinea vs micronesia catch / reporting
x <- scinames_excluding_tradeflows %>%
  filter(eez_iso3c == "FSM") %>%
  mutate(micronesia = 1)

y <- scinames_excluding_tradeflows %>% 
  filter(eez_iso3c == "PNG") %>%
  select(sciname_hs_modified) %>%
  mutate(papua = 1)

papua_all_columns <- scinames_excluding_tradeflows %>% 
  filter(eez_iso3c == "PNG")

z <- full_join(x, y)

only_in_papua <- z %>%
  filter(papua == 1, is.na(micronesia))

# only_in_papua <- only_in_papua %>%
#   select(sciname_hs_modified) %>%
#   left_join(papua_all_columns)

only_in_micronesia <- z %>%
  filter(micronesia == 1, is.na(papua))

micro_genus <- only_in_micronesia %>%
  pull(genus)

micro_subfamily <- only_in_micronesia %>%
  pull(subfamily)

micro_family <- only_in_micronesia %>%
  pull(family)

micro_order <- only_in_micronesia %>%
  pull(order)

micro_class <- only_in_micronesia %>%
  pull(class)

micro_superclass <- only_in_micronesia %>%
  pull(superclass)

micro_phylum <- only_in_micronesia %>%
  pull(phylum)

micro_kingdom <- only_in_micronesia %>%
  pull(kingdom)

 names_in_both <- only_in_papua %>%
  filter(sciname_hs_modified %in% micro_genus |
           sciname_hs_modified %in% micro_subfamily |
           sciname_hs_modified %in% micro_family |
           sciname_hs_modified %in% micro_order |
           sciname_hs_modified %in% micro_class |
           sciname_hs_modified %in% micro_superclass |
           sciname_hs_modified %in% micro_phylum |
           sciname_hs_modified %in% micro_kingdom) %>%
  select(sciname_hs_modified) %>%
  left_join(papua_all_columns) %>%
  select(sciname_hs_modified, common_name, taxa_level) %>%
   pull(sciname_hs_modified)
 
 x %>%
  filter(
    apply(.[, c("genus", "family", "order", "class")], 1, function(row) {
      # Check if any column contains a match in the list of scientific names
      any(str_detect(row, paste(names_in_both, collapse = "|")))
    })
  ) %>%
   pull(common_name)
 
x %>%
  filter(if_any(contains(names_in_both)))

x %>%
  filter(str_detect(common_name, "tuna"))

papua_all_columns %>%
  filter(str_detect(common_name, "tuna"))

papua_all_columns %>%
  filter(str_detect(class, "actinopterygii")) %>%
  slice(1,6)



####################
####################
####################

# Scenario 1
taxa_levels <- c("class", "order", "family", "genus", "species")
scenario_1 <- c()
for (i in 1:(length(taxa_levels) - 1)) {
  value <- scinames_excluding_tradeflows %>%
    mutate(
      species = case_when(
        str_count(sciname_hs_modified, " ") == 1 ~ str_split(sciname_hs_modified, " ") %>% 
          sapply(function(x) x[2]), # Extract second word if exactly two words
        TRUE ~ NA_character_ # Return NA if not two words
      )
    ) %>%
    filter(eez_iso3c == "FSM") %>%
    group_by_at(taxa_levels[i]) %>%  # Group by the current taxa level (e.g., class)
    filter(!is.na(get(taxa_levels[i]))) %>%  # Filter out NA values for the current level
    summarize(
      all_next_na = all(!is.na(get(taxa_levels[i + 1]))),  # Check if the next taxa level is NA
      .groups = "drop"
    ) %>%
    summarize(sum = sum(all_next_na)) %>% # Summarize how many rows have all NA for the next taxa level
    pull(sum)
  scenario_1 <- append(scenario_1, value)
}

####################
####################
####################


# Scenario 2

scenario_2 <- c()
for (i in 1:(length(taxa_levels) - 1)) {
  value <- scinames_excluding_tradeflows %>%
    mutate(
      species = case_when(
        str_count(sciname_hs_modified, " ") == 1 ~ str_split(sciname_hs_modified, " ") %>% 
          sapply(function(x) x[2]), # Extract second word if exactly two words
        TRUE ~ NA_character_ # Return NA if not two words
      )
    ) %>%
    group_by_at(taxa_levels[i]) %>%  # Group by the current taxa level (e.g., class)
    filter(!is.na(get(taxa_levels[i]))) %>%  # Filter out NA values for the current level
    summarize(
      all_next_na = all(is.na(get(taxa_levels[i + 1]))),  # Check if the next taxa level is NA
      .groups = "drop"
    ) %>%
    summarize(sum = sum(all_next_na)) %>% # Summarize how many rows have all NA for the next taxa level
    pull(sum)
  scenario_2 <- append(scenario_2, value)
}


scinames_excluding_tradeflows %>%
  mutate(
    species = case_when(
      str_count(sciname_hs_modified, " ") == 1 ~ str_split(sciname_hs_modified, " ") %>%
        sapply(function(x) x[2]), # Extract second word if exactly two words
      TRUE ~ NA_character_ # Return NA if not two words
    )
  ) %>%
  group_by(order) %>%
  filter(!is.na(order)) %>%
  summarize(
    all_genus_na = all(is.na(family)),  # Check if all rows for a class have NA in genus
    .groups = "drop"
  ) %>%
  summarize(sum = sum(all_genus_na))

####################
####################
####################

# Scenario 3
scenario_3 <- c()
for (i in 1:(length(taxa_levels) - 1)) {
  value <- scinames_excluding_tradeflows %>%
    mutate(
      species = case_when(
        str_count(sciname_hs_modified, " ") == 1 ~ str_split(sciname_hs_modified, " ") %>% 
          sapply(function(x) x[2]), # Extract second word if exactly two words
        TRUE ~ NA_character_ # Return NA if not two words
      )
    ) %>%
    group_by_at(taxa_levels[i]) %>%  # Group by the current taxa level (e.g., class)
    filter(!is.na(get(taxa_levels[i]))) %>%  # Filter out NA values for the current level
    summarize(
      all_next_na = any(is.na(get(taxa_levels[i + 1]))),  # Check if the next taxa level is NA
      .groups = "drop"
    ) %>%
    summarize(sum = sum(all_next_na)) %>% # Summarize how many rows have all NA for the next taxa level
    pull(sum)
  scenario_3 <- append(scenario_3, value)
}

# Correct scenario 3 counts (scenario 3 originally includes stuff from scenario 2, so subtract if 2 > 3)
for (i in 1:4) {
  if(scenario_3[i] >= scenario_2[i]) {
    scenario_3[i] <- scenario_3[i] - scenario_2[i]
  }
}

data.frame(missing_taxa = c(scenario_1, scenario_2, scenario_3),
           scenario = rep(c("1", "2", "3"), each = 4),
           taxa_level = c("Class", "Order", "Family", "Genus")) %>%
  ggplot(aes(x = factor(taxa_level, levels = c("Genus", "Family", "Order", "Class")), 
             y = missing_taxa, 
             fill = scenario)) +
  geom_col(position = "fill") +
  labs(x = "Taxa level", y = "Missing taxa", fill = "Scenario") +
  theme_light() +
  scale_fill_viridis_d(end = 0.8)

####################
####################
####################






scinames_excluding_tradeflows




scinames_excluding_tradeflows %>%
  mutate(
    species = case_when(
      str_count(sciname_hs_modified, " ") == 1 ~ str_split(sciname_hs_modified, " ") %>% 
        sapply(function(x) x[2]), # Extract second word if exactly two words
      TRUE ~ NA_character_ # Return NA if not two words
    )
  ) %>%
  filter(eez_iso3c == "FSM") %>%
  group_by(genus) %>%
  filter(!is.na(genus)) %>%
  distinct(class)

scinames_excluding_tradeflows %>%
  filter(eez_iso3c == "FSM") %>%
  group_by(family) %>%
  filter(!is.na(family)) %>%
  distinct(family)

```

```{r add in fishbase / sealifebase data connections}
# Create instances of fishbase/sealifebase data (if they don't already exist)
rmarkdown::render("../code/QuirozConnor_SGL_Obtain_Fishbase_Sealifebase_Data.Rmd")

# Read in fishbase/sealifebase data
fb_presences_country <- read_parquet("../data/fb_slb_data/fb_presences_country.parquet")
slb_presences_country <- read_parquet("../data/fb_slb_data/slb_presences_country.parquet")

fb_presences_faoareas <- read_parquet("../data/fb_slb_data/fb_presences_faoareas.parquet")
slb_presences_faoareas <- read_parquet("../data/fb_slb_data/slb_presences_faoareas.parquet")

fb_species_codes <- read_parquet("../data/fb_slb_data/fb_species_codes")
slb_species_codes <- read_parquet("../data/fb_slb_data/slb_species_codes.parquet")

# Modify sciname casing so that it can be joined to fishbase
scinames_excluding_tradeflows <- scinames_excluding_tradeflows %>%
  mutate(sciname_joinable_to_fishbase = str_to_title(word(sciname_hs_modified, 1)), 
         sciname_joinable_to_fishbase2 = word(sciname_hs_modified, 2), 
         sciname_joinable_to_fishbase = ifelse(
        is.na(sciname_joinable_to_fishbase2),
        sciname_joinable_to_fishbase,
        paste(sciname_joinable_to_fishbase, sciname_joinable_to_fishbase2))) %>%
  select(-sciname_joinable_to_fishbase2) %>%
  relocate(sciname_joinable_to_fishbase, .after = sciname_hs_modified)

# ***
# MAKING SURE ARTIS SCINAMES ALIGN WITH FISHBASE

# # of ARTIS unique ID's (includes higher taxonomic levels that aren't only species) - 1666 total IDs
length(unique(scinames_excluding_tradeflows$sciname_joinable_to_fishbase))

length(!is.na(unique(consumption$sciname_hs_modified)))

# # of ARTIS species (1326 species)
scinames_excluding_tradeflows %>%
  ungroup() %>%
  filter(str_detect(sciname_hs_modified, " ")) %>%
  distinct(sciname_hs_modified) %>%
  pull(sciname_hs_modified) %>%
  length()

# 1326 species with sciname_hs_modified variable
sum(str_detect(unique(na.omit(consumption_sciname$sciname_hs_modified)), " "))

# Unique entries in Fishbase (i.e., # of ARTIS species successfully joined to fishbase - 1382 species)
artis_fishbase_locations <- fb_presences_faoareas

# Total number of joined species succesfully from ARTIS
length(unique(artis_fishbase_locations$Species))
sum(str_detect(unique(artis_fishbase_locations$Species), " "))

# ***


# Get unique taxonomic entries (no repeats)
unique_taxonomy_entries <- scinames_excluding_tradeflows

# Determines whether something is reported to **at least** a given taxonomic level
unique_taxonomy_entries <- at_least_vars(unique_taxonomy_entries)

# Add in species binary Yes or no
unique_taxonomy_entries <- unique_taxonomy_entries %>%
  mutate(at_least_species = case_when(taxa_level == "species" ~ 1, TRUE ~ 0)) %>%
  relocate(at_least_species, .before = at_least_genus)

# Count taxonomic totals
taxa_unreported_props <- data.frame()
taxa_unreported_quantity <- data.frame()
for (i in levels) {
  amount <- unique_taxonomy_entries %>%
    ungroup() %>%
    summarize(sum = sum(!(!!sym(paste0("at_least_",i))))) %>%
    pull(sum)
  total <- length(unique_taxonomy_entries$sciname)
  prop <- amount / total
  taxa_unreported_props <- bind_rows(taxa_unreported_props, list(i, round(prop, 2)))
  taxa_unreported_quantity <- bind_rows(taxa_unreported_quantity, list(i, total))
}

# Rename taxa_total variables
taxa_unreported_props <- taxa_unreported_props %>%
  rename(taxa_level = "X.species.", prop = "X0.2")

taxa_unreported_quantity <- taxa_unreported_quantity %>%
  rename(taxa_level = "X.species.", prop = "X2232L")

# Reports proportion and quantities that are not reported to a given taxonomic level.
print(taxa_unreported_props)
print(taxa_unreported_quantity)

# METHOD 1: rfishbase::faoareas() - takes awhile to run thus commented
# fishbase_presences_faoareas <- taxa_presence_or_absence_faoareas(data = "fishbase")
# sealifebase_presences_faoareas <- taxa_presence_or_absence_faoareas(data = "sealifebase")
# 
# # Filter to only have sealifebase data (separate out sealifebase base using source variable)
# only_sealifebase <- sealifebase_presences_faoareas %>%
#   filter(source == "sealifebase")
# 
# # Get indexes where sealifebase found presences or absences
# sealifebase_presence_absences_indexes <- which(sealifebase_presences_faoareas$presence_or_absence %in% c(0,1))
# 
# # Select fishbase + unlinked NA data (excludes sealifebase)
# fishbase_minus_sealifebase <- fishbase_presences_faoareas[-sealifebase_presence_absences_indexes,]
# 
# # Merce fishbase / sealifebase presence data - this will be the data that we use to interpolate higher taxonomic resolutions!
# merged_presence_absence_data_faoareas <- bind_rows(fishbase_minus_sealifebase, only_sealifebase)
# 
# merged_presence_absence_data_faoareas %>%
#   count(presence_or_absence)


# METHOD 2: rfishbase::conutry()

# Obtain stats on fishbase/sealifebase data
taxa_presence_or_absence(data = "fishbase", obtain_stats = TRUE)
taxa_presence_or_absence(data = "sealifebase", obtain_stats = TRUE)

# Create presence/absence data
fishbase_presences_country <- taxa_presence_or_absence(data = "fishbase")
sealifebase_presences_country <- taxa_presence_or_absence(data = "sealifebase")

# Number of rows in ARTIS data (fishbase + sealifebase presence data)
nrow(fishbase_presences_country)
nrow(sealifebase_presences_country)

# Check to see if fishbase and sealifebase have any overlapping species (they do not!)
any(sealifebase_presences_country$Species %in% artis_fishbase_locations$Species)

# Combine fishbase/sealifebase data
merged_presence_absence_data_country <- bind_rows(fishbase_presences_country[-which(sealifebase_presences_country$source == "sealifebase"),], sealifebase_presences_country %>% filter(source == "sealifebase"))

# Add true species column
merged_presence_absence_data_country <- merged_presence_absence_data_country %>%
  mutate(species = case_when(str_detect(sciname_hs_modified, " ") ~ sapply(str_split(sciname_hs_modified, " "), `[`, 2),
                             TRUE ~ NA))



# Determine if lower resolution taxa are in an eez (e.g., if a species for a given country is found there that is also a lower resolution taxa like actinoptergyii, then all actinoptergyii or higher will be found in that country) -

# List of ARTIS species that aren't matched to either fishbase or sealifebase
# Create a dataset to identify whether a species comes from ARTIS or slb/fb
species_determination <- full_join(
  bind_rows(fb_presences_country %>% 
              mutate(source = "fishbase"), 
            slb_presences_country %>% 
              mutate(source = "sealifebase")) %>%
    mutate(ScientificName = tolower(ScientificName)) %>%
    select(ScientificName) %>%
    distinct() %>% 
    mutate(fb_slb = 1), 
  sciname %>% 
    select(sciname, common_name) %>%
    filter(str_detect(sciname, " ")) %>% 
    distinct() %>% 
    mutate(artis = 1), 
  by = c("ScientificName" = "sciname")) 

# Species in FB/SLB but not ARTIS
artis_species_not_in_fbslb <- species_determination %>%
  filter(is.na(fb_slb) == TRUE, artis == 1) %>%
  pull(ScientificName)

fbslb_species_not_in_artis <- species_determination %>%
  filter(fb_slb == 1, is.na(artis) == TRUE) %>%
  pull(ScientificName)
  
pa_only_artis <- merged_presence_absence_data_country %>%
  mutate(presence_or_absence = case_when(sciname_joinable_to_fishbase %in% species_not_in_artis ~ NA, TRUE ~ presence_or_absence))

presence_absence_data_linked <- data.frame()
for (i in unique(pa_only_artis$eez_iso3c)) {
  # Group data by eez country
  sliced_data <- pa_only_artis %>%
  filter(eez_iso3c == sym(i))

  # Create updated presence on sliced data
  sliced_data_for_merging <- sliced_data %>%
  mutate(unique_vals = str_replace_all(paste0(filter(., presence_or_absence == 1) %>% select(sciname_hs_modified, species, genus, subfamily, family, order, class, superclass, phylum, kingdom) %>%
  unlist() %>%
  unique(), collapse = " "), "[A-Z]", ""), presence_or_absence_all_taxa = case_when(sciname_hs_modified %in% species_not_in_artis ~ NA, 
presence_or_absence == 1 ~ 1,
str_detect(unique_vals, sciname_hs_modified) ~ 1,
                                                                                    TRUE ~ 0))

  # Combine rows of each country
  presence_absence_data_linked <- bind_rows(presence_absence_data_linked, sliced_data_for_merging)

}

# Count Number of presences/absences in filled in presence data
presence_absence_data_linked <- presence_absence_data_linked %>%
  relocate(presence_or_absence_all_taxa, .after = presence_or_absence)

# Count number of total presences / absences across ALL taxa levels
presence_absence_data_linked %>%
  count(presence_or_absence_all_taxa)

# List of **linked** countries proportions of stock reported as absent
linked_props <- presence_absence_data_linked %>%
  group_by(eez_iso3c) %>%
  distinct(sciname_hs_modified, .keep_all = TRUE) %>%
  select(sciname_hs_modified, presence_or_absence_all_taxa) %>%
  count(presence_or_absence_all_taxa) %>%
  mutate(presence_or_absence_all_taxa = as.character(presence_or_absence_all_taxa)) %>%
  pivot_wider(values_from = n, names_from = presence_or_absence_all_taxa, names_glue = "quantity_{presence_or_absence_all_taxa}") %>%
  mutate(prop_missing =  quantity_0 / (quantity_0 + quantity_1))

# See which countries have only absences and no presences
presence_absence_data_linked %>%
  group_by(eez_iso3c) %>%
  distinct(sciname_hs_modified, .keep_all = TRUE) %>%
  select(sciname_hs_modified, presence_or_absence_all_taxa) %>%
  count(presence_or_absence_all_taxa) %>%
  mutate(presence_or_absence_all_taxa = as.character(presence_or_absence_all_taxa)) %>%
  pivot_wider(values_from = n, names_from = presence_or_absence_all_taxa, names_glue = "quantity_{presence_or_absence_all_taxa}") %>%
  mutate(prop_missing =  quantity_0 / (quantity_0 + quantity_1)) %>%
  filter(is.na(prop_missing) & is.na(quantity_1)) %>%
  rename(number_absences = "quantity_0", number_presences = "quantity_1")

# Get species that aren't apart of artis, but are only included in fishbase/sealife base (extra species locations we need to )
pa_excluding_artis <- merged_presence_absence_data_country %>%
  filter(str_detect(sciname_joinable_to_fishbase, " ") & !(joined %in% c("only in artis", "both")))

# See which species aren't matched
# 44 species that aren't mathed to either fishbase or sealifebase
pa_only_artis %>%
  filter(str_detect(sciname_joinable_to_fishbase, " ") & is.na(presence_or_absence)) %>%
  distinct(sciname_joinable_to_fishbase)

# Sum: 93447 - remove species from ARTIS that aren't in fishbase/sealifebase
sum(pa_excluding_artis %>%
  distinct(sciname_joinable_to_fishbase) %>%
  summarize(n = n()) %>%
  pull(n),

pa_only_artis %>%
  filter(str_detect(sciname_joinable_to_fishbase, " ") & !is.na(presence_or_absence)) %>%
  distinct(sciname_joinable_to_fishbase) %>%
  drop_na() %>%
  summarize(n = n()) %>%
  pull(n))

# Sum: 93447
sum(fb_presences_country %>%
      filter(Status %in% c("native", "Native", "introduced", "endemic") & !is.na(country)) %>%
  distinct(Species) %>%
    drop_na() %>%
  summarize(n = n()) %>%
  pull(n),
slb_presences_country %>%
  filter(Status %in% c("native", "Native", "introduced", "endemic") & !is.na(country)) %>%
  distinct(Species) %>%
  drop_na() %>%
  summarize(n = n()) %>%
  pull(n))

# Determine different commercial usages (need to only include commercial fishes for our analysis)
fb_presences_country %>%
  distinct(Importance)

# Get only non-artis species that are of commercial interest
fb_slb_commercial_interests <-  anti_join(
  bind_rows(fb_presences_country %>%
              mutate(source = "fishbase", 
                     ScientificName = str_to_lower(ScientificName)), 
            slb_presences_country %>% 
              mutate(source = "sealifebase",
                     ScientificName = str_to_lower(ScientificName))), 
  sciname %>% 
    filter(str_detect(sciname, " ")) %>% 
    distinct(), 
  by = c("ScientificName" = "sciname")) %>%
  filter((Status %in% c("native", "Native", "introduced", "endemic") & !is.na(country)) & (Importance %in% c("minor commercial", "highly commercial", "commercial", "subsistence fisheries", "of potential interest")))

# Convert fb/slb commercial marine country names to iso3c codes + filter out countries NOT in ARTIS
fb_slb_commercial_interests <- fb_slb_commercial_interests %>%
  select(country, ScientificName, Species, Genus, SubFamily, Family, Order, Class, SuperClass, Phylum, Kingdom) %>%
    mutate(country = countrycode(country, origin = 'country.name', destination = 'iso3c')) %>%
    filter(country %in% unique(pa_only_artis$eez_iso3c)) %>%
    group_by(ScientificName) %>%
  mutate(countries_found = paste0(country, collapse = " ")) %>%
  distinct(ScientificName, .keep_all = TRUE) %>%
  mutate(ScientificName = str_to_lower(ScientificName), 
         Species = str_to_lower(Species), 
         Genus = str_to_lower(Genus), 
         SubFamily = str_to_lower(SubFamily), 
         Family = str_to_lower(Family), 
         Order = str_to_lower(Order), 
         Class = str_to_lower(Class), 
         SuperClass = str_to_lower(SuperClass), 
         Phylum = str_to_lower(Phylum), 
         Kingdom = str_to_lower(Kingdom), 
         presence_or_absence = 1) %>%
  rename(sciname_hs_modified = "ScientificName", 
         species = "Species", 
         genus = "Genus", 
         subfamily = "SubFamily", 
         family = "Family", 
         order = "Order", 
         class = "Class", 
         superclass = "SuperClass", 
         phylum = "Phylum", 
         kingdom = "Kingdom", 
         eez_iso3c = "country")

# FB/SLB does not have superclass/phylum/kingdom, so we will first (1) match with artis to obtain superclass, phylum, and kingdom, and fill in the rest with rgbif

# Get class names for fb_slb data (will combine with artis_scinames to get phylum, kingdom, which fishbase does not have)
class_taxa_names <- fb_slb_commercial_interests %>%
  ungroup() %>%
  distinct(class) %>%
  pull(class)

# Create an empty list
superclass_phylum_kingdom <- data.frame(class = class_taxa_names, superclass = NA_character_, phylum = NA_character_, kingdom = NA_character_)
for (i in class_taxa_names) {
  matched_scinames <- sciname %>%
    filter(class == i) %>%
    distinct(superclass, phylum, kingdom) %>%
    select(superclass, phylum, kingdom)
  
  # Check to see if dataframe is empty or not
  if (dim(matched_scinames)[1] == 0) {
    matched_scinames <- data.frame(superclass = NA_character_,
                                            phylum = NA_character_,
                                            kingdom = NA_character_)
  }
  k <- which(class_taxa_names == i) # Currentl index in class list
  # Add entries into a list
  superclass_phylum_kingdom$superclass[k] <- matched_scinames$superclass
  superclass_phylum_kingdom$phylum[k] <- matched_scinames$phylum
  superclass_phylum_kingdom$kingdom[k] <- matched_scinames$kingdom
}

taxa_to_be_filled <- superclass_phylum_kingdom %>%
  filter(is.na(superclass) |
         is.na(phylum) |
         is.na(kingdom))

# New script to refer to to obtain Global Biodiversity Information Facility (rgbif) taxa data - refer to "accepted" column to filter for target species that we will be getting the missing phylum / kingdom names

# taxa_to_be_filled is fed through this script to fill in phylum/kingdom names (takes awhile hence why another script was created)
rmarkdown::render("../code/QuirozConnor_SGL_Obtain_gbif_Data.Rmd")
taxa_to_be_filled_gbif <- read_parquet("../data/rgbif_data/taxa_to_be_filled_gbif.parquet")

# Combine rows fb/slb unlinked names that didn't need filling in + filled in phylum/kingdom names obtained via gbif
filled_fb_slb_taxa <- bind_rows(superclass_phylum_kingdom %>%
  filter(!is.na(superclass) &
         !is.na(phylum) &
         !is.na(kingdom)), taxa_to_be_filled_gbif)


# Fill in the rest of the phylum/kingdom names with gbif
fb_slb_commercial_interests <- left_join(fb_slb_commercial_interests, filled_fb_slb_taxa, by = "class") %>%
mutate(
  superclass = coalesce(superclass.x, superclass.y), # If superclass.x is NA, take superclass.y
  phylum = coalesce(phylum.x, phylum.y),  # Similarly for phylum
  kingdom = coalesce(kingdom.x, kingdom.y)) %>% # Similarly for kingdom
select(-phylum.x, -phylum.y, -kingdom.x, -kingdom.y, -superclass.x, -superclass.y)

# Re-determine if lower resolution taxa are present with both ARTIS + non-ARTIS species
only_artis_1 <- merged_presence_absence_data_country

# Combine only artis species with fb/slb commercial species NOT in artis (used to increase amount of presences in data via country function)
pa_only_artis <- bind_rows(only_artis_1, fb_slb_commercial_interests %>% mutate(source = "unlinked")) %>%
  mutate(presence_or_absence = case_when(sciname_joinable_to_fishbase %in% species_not_in_artis ~ NA, TRUE ~ presence_or_absence))
presence_absence_data_linked_unlinked <- data.frame()

for (i in unique(pa_only_artis$eez_iso3c)) {
  # Group data by eez country
  sliced_data <- pa_only_artis %>%
  filter(eez_iso3c == i)

  # Create updated presence on sliced data
  sliced_data_for_merging <- sliced_data %>%
  mutate(unique_vals = str_replace_all(paste0(filter(., presence_or_absence == 1) %>% select(sciname_hs_modified, species, genus, subfamily, family, order, class, superclass, phylum, kingdom) %>%
  unlist() %>%
  unique(), collapse = " "), "[A-Z]", ""), 
  presence_or_absence_all_taxa = case_when(str_detect(unique_vals, sciname_hs_modified) ~ 1,
sciname_hs_modified %in% species_not_in_artis ~ NA,
TRUE ~ 0))

  # Combine rows of each country
  presence_absence_data_linked_unlinked <- bind_rows(presence_absence_data_linked_unlinked, sliced_data_for_merging)

}

# Count Number of presences/absences in filled in presence data
presence_absence_data_linked_unlinked <- presence_absence_data_linked_unlinked %>%
  relocate(presence_or_absence_all_taxa, .after = presence_or_absence)

# Code that displays ARTIS taxa are present/absent
presence_absence_data_linked_unlinked %>%
  filter(source != "unlinked" | is.na(source)) %>%
  count(presence_or_absence_all_taxa)

# See which countries are absent
linked_unlinked_props <- presence_absence_data_linked_unlinked %>%
  group_by(eez_iso3c) %>%
  distinct(sciname_hs_modified, .keep_all = TRUE) %>%
  select(sciname_hs_modified, presence_or_absence_all_taxa) %>%
  count(presence_or_absence_all_taxa) %>%
  mutate(presence_or_absence_all_taxa = as.character(presence_or_absence_all_taxa)) %>%
  pivot_wider(values_from = n, names_from = presence_or_absence_all_taxa, names_glue = "quantity_{presence_or_absence_all_taxa}") %>%
  mutate(prop_missing =  quantity_0 / (quantity_0 + quantity_1)) %>%
  rename(number_absences = "quantity_0", number_presences = "quantity_1")

linked_unlinked_props %>%
  filter(is.na(prop_missing) & is.na(number_presences))

# Get data over to Jessica
# fb_slb_species_data <- bind_rows(fb_presences_country, slb_presences_country)
# fb_slb_species_data <- fb_slb_species_data %>%
#   rename(Sciname = Species, Species = TrueSpecies)
# str(fb_slb_species_data)
# write_parquet(fb_slb_species_data, "../data/fb_slb_species_data.parquet")
# write_csv(fb_slb_species_data, "../data/fb_slb_species_data.csv")

# Get fb/slb countries
fb_slb_countries <- bind_rows(fb_presences_country ,slb_presences_country) %>%
  mutate(country = countrycode(country, origin = 'country.name', destination = 'iso3c')) %>%
  distinct(country) %>% arrange(country)
  
# Get artis countries
artis_countries <- consumption %>%
distinct(consumer_iso3c) %>%
  arrange(consumer_iso3c)

# Join artis/fb_slb countries
joined_countries <- full_join(artis_countries %>% mutate(artis = 1), fb_slb_countries %>% mutate(fb_slb = 1), by = c("consumer_iso3c" = "country"))

# Countries that both artis/fb_slb has
x <- joined_countries %>%
  filter(artis == 1 & fb_slb == 1) %>%
  pull(consumer_iso3c)

# Countries that ARTIS has that fb_slb doesn't have
joined_countries %>%
  filter(artis == 1 & is.na(fb_slb))

unaligned_names <- read.csv("../data/unmatched_names.csv")
unaligned_names <- unaligned_names %>% pull(fb_slb_scientific_name)

# Number of fb/slb rows that are not include in analysus due to unaligned countries/scinames
bind_rows(fb_presences_country, slb_presences_country) %>%
  mutate(country = countrycode(country, origin = 'country.name', destination = 'iso3c'), ScientificName = str_to_lower(ScientificName)) %>%
  filter((!(country %in% x) | is.na(country)) | ScientificName %in% unaligned_names)

conusmption_sciname

# Get data over to Jessica
# fb_slb_species_data <- bind_rows(fb_presences_country, slb_presences_country)
# fb_slb_species_data <- fb_slb_species_data %>%
#   rename(Sciname = Species, Species = TrueSpecies)
# str(fb_slb_species_data)
# write_parquet(fb_slb_species_data, "../data/fb_slb_species_data.parquet")
# write_csv(fb_slb_species_data, "../data/fb_slb_species_data.csv")

# Get fb/slb countries
fb_slb_countries <- bind_rows(fb_presences_country ,slb_presences_country) %>%
  mutate(country = countrycode(country, origin = 'country.name', destination = 'iso3c')) %>%
  distinct(country) %>% arrange(country)
  
# Get artis countries
artis_countries <- consumption %>%
distinct(consumer_iso3c) %>%
  arrange(consumer_iso3c)

# Join artis/fb_slb countries
joined_countries <- full_join(artis_countries %>% mutate(artis = 1), fb_slb_countries %>% mutate(fb_slb = 1), by = c("consumer_iso3c" = "country"))

# Countries that both artis/fb_slb has
x <- joined_countries %>%
  filter(artis == 1 & fb_slb == 1) %>%
  pull(consumer_iso3c)

# Countries that ARTIS has that fb_slb doesn't have
joined_countries %>%
  filter(artis == 1 & is.na(fb_slb))

unaligned_names <- read.csv("../data/unmatched_names.csv")
unaligned_names <- unaligned_names %>% pull(fb_slb_scientific_name)

# Number of fb/slb rows that are not include in analysus due to unaligned countries/scinames
bind_rows(fb_presences_country, slb_presences_country) %>%
  mutate(country = countrycode(country, origin = 'country.name', destination = 'iso3c'), ScientificName = str_to_lower(ScientificName)) %>%
  filter((!(country %in% x) | is.na(country)) | ScientificName %in% unaligned_names)
```

```{r consuption data reading}

# consumption_all_years <- consumption

consumption <- consumption %>%
  filter(year == 2019)

# Read in taxonomic data
sciname <- read.csv("../data/sciname.csv")

# Get unique taxa names by eez (excluding trade flows)
scinames_excluding_tradeflows <- consumption %>%
  ungroup() %>%
  distinct(eez_iso3c, sciname_hs_modified) %>%
  left_join(sciname, by = c("sciname_hs_modified" = "sciname")) %>%
  rename(sciname = "sciname_hs_modified") %>%
  taxa_level_vars() %>%
  rename(sciname_hs_modified = "sciname") %>%
  filter(!is.na(sciname_hs_modified)) %>%
  ungroup()

# Create consumption imports data
consumption_imports <- consumption %>%
  

# Combine consumption and taxonomic data
consumption_sciname <- left_join(consumption, sciname, by = "sciname")

# Create phylogenetic variables
consumption_sciname <- taxa_level_vars(consumption_sciname)

consumption_sciname <- consumption_sciname %>%
  exploreARTIS::add_region("consumer_iso3c", region.col.name = "region")

# Read in  Adaptive Capacity data
hdi <- read.csv("../data/hdi.csv")

hdi <- hdi %>%
  rename(consumer_iso3c = "country") %>%
  select(-date_obtained)

# Convert country names to iso3c codes
for (i in 1:length(hdi$consumer_iso3c)) {
  hdi$consumer_iso3c[i] <- countryname(hdi$consumer_iso3c[i], destination = "iso3c")
}

# Variable names for consumption
names(consumption)

# Looking at total weights per country (aggregating species weight in 2019)
con_weight <- consumption %>%
  filter(consumer_iso3c != producer_iso3c & str_detect(sciname, pattern = "\ ")) %>%
  group_by(consumer_iso3c) %>%
  mutate(live_weight_t = as.numeric(live_weight_t)) %>%
  summarize(total_weight = sum(live_weight_t)) %>%
  arrange(desc(total_weight))

# Shannon diversity of countries' imports
con_shannon <- consumption_sciname %>%
  filter(consumer_iso3c != producer_iso3c & str_detect(sciname, pattern = "\ ")) %>%
  group_by(consumer_iso3c, genus) %>%
  summarize(genus_total = sum(live_weight_t)) %>%
  group_by(consumer_iso3c) %>%
  mutate(genus_total_country = sum(genus_total)) %>%
  ungroup() %>%
  mutate(pi = genus_total / genus_total_country, pi_lnpi = pi * log(pi)) %>%
  group_by(consumer_iso3c) %>%
  summarize(shannon = -sum(pi_lnpi))

# Join quantity and diversity
con_joined <- left_join(con_weight, con_shannon, by = "consumer_iso3c")

# Add in hdi values to joined dataset
con_joined <- left_join(con_joined, hdi, by = "consumer_iso3c")

# Store phylogenetic levels in a vector
levels <- c()
levels <- unique(consumption_sciname$taxa_level)

# Remove superclass (only 1 according to taxa_level variable) and species (different analysis to get prop)
levels <- levels[!(levels %in% c("superclass", "species", "phylum"))]

# Proportions of producing countries reporting to **at least** that taxonomic level (should be cumulative probabilities)
# Set up whether a producing country reported to at least a certain level (1 means it could also go lower (e.g., 1 in class means it could be just class or goes all the way to species))
consumption_sciname <- at_least_vars(data = consumption_sciname) %>%
    rename(consumer_iso3c = producer_iso3c)

# Add back in species
levels <- c("species", "genus", "family", "order", "class")

# Percentage of countries that report to species (no species column in sciname data - have to do different way from rest of taxonomic groups)
con_joined <- con_joined %>%
  mutate(prop_at_least_species = prop_exactly_species)

# Update joined dataset to have log transformed total weight as a variable
con_joined <- con_joined %>%
  mutate(log_weight = log(total_weight))

# Add in region (e.g., North America, Asia, etc.)
con_joined <- con_joined %>%
  exploreARTIS::add_region("consumer_iso3c", region.col.name = "region")

# Consumption data without NA's (for correlation plots)
con_na_removed <- con_joined %>%
  drop_na()

# Remove NA region
con_joined <- con_joined %>%
  drop_na(region)

# Sort countries in alphabetical order
con_joined %>%
  arrange(-desc(consumer_iso3c))

# Prints out number of unique values per phylogenetic group
for (i in c(19, 21, 22, 23)) {
  print(c(length(unique(na.omit(consumption_sciname[[i]]))), names(consumption_sciname)[i]))
}

# Join consumption dataset to future climate data
consumption_sciname_future <- left_join(consumption_sciname, df, by = c("eez_iso3c", "sciname"))

length(unique(consumption_sciname$eez_iso3c))
length(unique(df$eez_iso3c))
mask <- unique(consumption_sciname$eez_iso3c) %in% unique(c(df$eez_iso3c))
unique(consumption_sciname$eez_iso3c)[!mask]

length(unique(consumption_sciname$family))
# separate question for whether trade overall increases or homogenizes diets (e.g., need marine capture / aquaculture)
# 503 families in total (all capture + aquaculture)

# Number of orders by country
consumption_sciname %>%
  group_by(eez_iso3c) %>%
  summarize(total_order = length(unique(order)))
```


```{r INTERPOLATION}
# Create data that is prepared for interpolation (slb + artis presence data with taxa names for target taxa level and **above**)
# Our goal: Estimate taxa levels below ones that aren't high resolution (e.g., order --> family)
data_for_interpolation <- taxa_level_vars(data = presence_absence_data_linked_unlinked, taxa_var = "sciname_hs_modified") %>%
  at_least_vars(grouping = "eez_iso3c", taxa_var = "sciname_hs_modified") %>%
  select(-unique_vals, -presence_or_absence, -countries_found, -isscaap) %>%
  relocate(species, .before = "genus")


data_for_interpolation <- left_join(data_for_interpolation, linked_unlinked_props, by = "eez_iso3c") %>%
  select(-number_absences, -number_presences, -quantity_NA)

# Linear model measuring prop missing versus prop of stock reported to species
lm(prop_missing ~ prop_at_least_species, data = data_for_interpolation) %>%
  summary()

# See which countries have the most missing taxa
data_for_interpolation %>%
  filter(source != "unlinked" | is.na(source)) %>%
  group_by(eez_iso3c) %>%
  distinct(prop_missing) %>%
  arrange(-prop_missing)

data_for_interpolation %>%
  filter(eez_iso3c == "PSE") %>%
  select(sciname_hs_modified, taxa_level, presence_or_absence_all_taxa, family, class)

consumption_sciname %>% ungroup() %>% filter(eez_iso3c == "USA") %>%
  mutate(species = map_chr(sciname_hs_modified, ~ str_split(.x, " ")[[1]][2])) %>%
  select(sciname_hs_modified, eez_iso3c, species, genus, family, order, class, phylum, kingdom, taxa_level) %>% 
  distinct() %>%
  filter(!is.na(sciname_hs_modified)) %>%
  group_by(class) %>%
  distinct(species) %>%
  summarize(num_species = n_distinct(species)) %>%
  arrange(num_species) %>%
    filter(is.na(species) & count(., class) == 1)
```


```{r iterative process for checking diversity across taxonomic levels (e.g., genus, family, etc.)}
for (i in levels) {
  # Shannon diversity of countries' imports
  con_iteration <- consumption_sciname %>%
    filter(year == 2019 &
             consumer_iso3c != producer_iso3c & taxa_level == i) %>%
    group_by(consumer_iso3c, sciname) %>%
    summarize(genus_total = sum(live_weight_t)) %>%
    group_by(consumer_iso3c) %>%
    mutate(genus_total_country = sum(genus_total)) %>%
    ungroup() %>%
    mutate(pi = genus_total / genus_total_country,
           pi_lnpi = pi * log(pi)) %>%
    group_by(consumer_iso3c) %>%
    summarize(shannon_custom = -sum(pi_lnpi))
  
# Create plot
plot_iteration <-
  left_join(con_joined, con_iteration, by = "consumer_iso3c") %>%
  ggplot(aes(x = shannon_custom)) +
  geom_histogram(color = "black") +
  labs(x = paste0("Shannon diversity (", i, ")"), y = "Frequency") +
  theme_light()

boxplot_iteration <-
  left_join(con_joined, con_iteration, by = "consumer_iso3c") %>%
  ggplot(aes(x = region, y = shannon_custom, fill = region)) +
  geom_violin(alpha = 0.5) +
  geom_point() +
  labs(x = "", y = paste0("Shannon diversity (", i, ")")) +
  guides(fill = "none") +
  scale_fill_manual(values = artis_palette(length(unique(con_joined$region)))) +
  theme_light()

# Set median value for median line in graph
col_name_exactly <- sym(paste0("prop_exactly_", i))
median_value_exactly <- con_joined %>%
  summarise(median = median(!!col_name_exactly, na.rm = TRUE)) %>%
  pull(median)

# Set median value for median line in graph
col_name_at_least <- sym(paste0("prop_at_least_", i))
median_value_at_least <- con_joined %>%
  summarise(median = median(!!col_name_at_least, na.rm = TRUE)) %>%
  pull(median)

prop_exactly_taxalevel_versus_hdi <- con_joined %>%
  ggplot(aes(
    x = hdi,
    y = .data[[paste0("prop_exactly_", i)]],
    color = region,
    size = shannon
  )) +
  scale_color_manual(values = artis_palette(length(unique(con_joined$region)))) +
  geom_point() +
  theme_light() +
  labs(color = "",
       x = "Human Development Index",
       y = paste0("Proportion of production\nreported to exactly ", i),
       size = paste0("Shannon diversity (", i, ")")) +
  scale_size(range = c(0, 2)) +
  ylim(0.0, 1.0) +
  geom_abline(aes(intercept = median_value_exactly, slope = 0), linetype = 2, size = 1.1, alpha = 0.5) +
  guides(color = guide_legend(title = paste0("Median proportion\nreported: ", round(median_value_exactly, 2)), title.theme = element_text(face = "bold.italic"), order = 1), size = guide_legend(order = 2))

prop_at_least_taxalevel_versus_weight <- con_joined %>%
  ggplot(aes(x = log(total_weight), y = .data[[paste0("prop_at_least_", i)]], color = region, size = hdi)) +
  scale_color_manual(values = artis_palette(length(unique(con_joined$region)))) +
  geom_point()+
  theme_light() +
  labs(color = "", x = "Log transformed total consumed \nseafood weight (tons)", y = paste0("Proportion of production\nreported to at least ", i), size = "HDI") +
  scale_size(range = c(0,2)) +
  ylim(0.0, 1.0) +
  geom_abline(aes(intercept = median_value_at_least, slope = 0), linetype = 2, size = 1.1, alpha = 0.5) +
  guides(color = guide_legend(title = paste0("Median proportion\nreported: ", round(median_value_at_least, 2)), title.theme = element_text(face = "bold.italic"), order = 1), size = guide_legend(order = 2))

prop_at_least_taxalevel_versus_hdi <- con_joined %>%
  ggplot(aes(
    x = hdi,
    y = .data[[paste0("prop_at_least_", i)]],
    color = region,
    size = shannon
  )) +
  scale_color_manual(values = artis_palette(length(unique(con_joined$region)))) +
  geom_point() +
  theme_light() +
  labs(color = "",
       x = "Human Development Index",
       y = paste0("Proportion of production\nreported to at least ", i),
       size = paste0("Shannon diversity (", i, ")")) +
  scale_size(range = c(0, 2)) +
  ylim(0.0, 1.0) +
  geom_abline(aes(intercept = median_value_at_least, slope = 0), linetype = 2, size = 1.1, alpha = 0.5) +
  guides(color = guide_legend(title = paste0("Median proportion\nreported: ", round(median_value_at_least, 2)), title.theme = element_text(face = "bold.italic"), order = 1), size = guide_legend(order = 2))
  
  # Print plot
  print(plot_iteration)
  print(boxplot_iteration)

  # Shannon sd
  shannon_sd <- left_join(con_joined, con_iteration, by = "consumer_iso3c") %>% pull(shannon_custom) %>% sd()
  # print(paste0(i, " standard deviation: ", signif(shannon_sd, 3)))

  # Shannon max/min
  shannon_max <- con_iteration %>% pull(shannon_custom) %>% max()
  shannon_min <- con_iteration %>% pull(shannon_custom) %>% min()
  print(paste0(i, " shannon [min, max]: [", round(shannon_min, 2), ", ", round(shannon_max, 2), "]"))
  print(con_iteration)
  
  ggsave(paste0("../images/prop_exactly_",i , "_versus_hdi.jpg"), plot = prop_exactly_taxalevel_versus_hdi, device = "jpeg", height = 4, width = 6, units = "in")
  ggsave(paste0("../images/prop_at_least_",i , "_versus_weight.jpg"), plot = prop_at_least_taxalevel_versus_weight, device = "jpeg", height = 4, width = 6, units = "in")
  ggsave(paste0("../images/prop_at_least_",i , "_versus_hdi.jpg"), plot = prop_at_least_taxalevel_versus_hdi, device = "jpeg", height = 4, width = 6, units = "in")
}
```



```{r data visualization + analysis}
# Top 10 total seafood weights by country
(country_weights <- con_joined %>%
  arrange(desc(total_weight)) %>%
  select(consumer_iso3c, total_weight) %>%
  top_n(10) %>%
  ggplot(aes(x = total_weight, 
             y = fct_reorder(consumer_iso3c, desc(-total_weight)))) +
  geom_col() +
  labs(x = "Total seafood weight (tons)", y = "Consuming country (imports)") +
  theme_light())

# Top 10 most diverse seafood by country 
(country_diversities <- con_joined %>%
  arrange(desc(shannon)) %>%
  select(consumer_iso3c, shannon) %>%
  top_n(10) %>%
  ggplot(aes(x = shannon, 
             y = fct_reorder(consumer_iso3c, desc(-shannon)))) +
  geom_col() +
  labs(x = "Shannon Diversity", y = "Consuming country (imports)") +
  theme_light())

# Relationship between shannon diversity and the total weight by country
(shannon_versus_weight <- con_joined %>%
  ggplot(aes(x = log(total_weight), y = shannon, color = hdi)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_color_viridis_c() +
  facet_wrap(~ region) +
  theme_light() +
  labs(x = "Log transformed total seafood weight (tons)", y = "Shannon diversity (species)", color = "HDI"))

# Props reported by region by taxonomic resolution
(prop_versus_tax_versus_country <- con_joined %>%
  pivot_longer(cols = c("prop_at_least_species","prop_at_least_genus","prop_at_least_family","prop_at_least_order"), names_to = "level", values_to = "prop") %>%
  mutate(level = str_remove(level, "prop_at_least_"), level = str_to_title(level), level = factor(level, levels = c("Order", "Family", "Genus", "Species"))) %>%
  ggplot(aes(x = reorder(level, -prop), y = prop, fill = region)) +
  geom_boxplot() +
  scale_fill_manual(values = artis_palette(length(unique(con_joined$region)))) +
  theme_light() +
  labs(x = "Taxonomic level", y = "Proportion of production\nreported to at least target\ntaxonomic level", fill = "Region"))

# % countries stock reported as absent (only including ARTIS linked fb/slb species)
(prop_absences_linked <- linked_props %>%
  ggplot(aes(x = prop_missing)) +
  geom_boxplot(fill = artis_palette(1)) +
  labs(x = "Prop of countries' stock reported as absent\n(Fishbase/Sealifebase") +
  theme_light() +
      theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()))

# % countries stock reported as absent (ARTIS linked + unlinkedfb/slb species)
(prop_absences_linked_unlinked <- linked_unlinked_props %>%
  ggplot(aes(x = prop_missing)) +
  geom_boxplot(fill = artis_palette(1)) +
  labs(x = "Prop of countries' stock reported as absent\n(Fishbase/Sealifebase") +
  theme_light() +
      theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()))

# Create maps
(prop_map_linked <- create_map(linked_props) + 
  labs(fill = "Prop of taxa reported as absent"))
 
(prop_map_linked_unlinked <- create_map(linked_unlinked_props) +
  labs(fill = "Prop of taxa reported as absent"))

# Prop taxa repoted vs prop absences
 for (i in c("species", "genus", "family", "order", "class", "phylum", "kingdom")) {
  graph <- data_for_interpolation %>%
  group_by(eez_iso3c) %>%
  distinct(prop_missing, !!sym(paste0("prop_at_least_", i))) %>%
  exploreARTIS::add_region("eez_iso3c", region.col.name = "region") %>%
  ggplot(aes(y = prop_missing, x = !!sym(paste0("prop_at_least_", i)), color = region)) +
  geom_point() +
  scale_color_manual(values = artis_palette(6)) +
  theme_light() +
  labs(x = paste0("Proportion EEZ taxa reported to ", i), y = "Proportion reported as absent", color = "Region") +
    xlim(0,1)
  
  ggsave(paste0("../images/prop_absences_vs_prop_", i, ".jpg"), plot = graph, device = "jpeg", width = 6, height = 4)
 }

# Violin plots of consuming countries' trade dependencies
consumer_foreign_dependencies %>%
  mutate(foreign_dependency = foreign_dependency * 100) %>%
  exploreARTIS::add_region("consumer_iso3c", region.col.name = "region") %>%
  filter(!is.na(region)) %>%
  ggplot(aes(x = region, y = foreign_dependency, fill = region)) +
  geom_violin(alpha = 0.5) +
  geom_point() +
  labs(x = "", y = "% foreign dependency") +
  guides(fill = "none") +
  theme_light() +
  scale_fill_manual(values = artis_palette(6))

# Foreign dependency of all consumer countries histgoram
consumer_foreign_dependencies %>%
  ggplot(aes(x = foreign_dependency)) +
  geom_histogram(color = "black") +
  labs(x = "Proportion foreign dependency", y = "# consuming conutries") +
  theme_light()

# Consumer stock change graph
(consumer_stock_change_graph <- consumer_stock_change %>%
  ggplot(aes(y = region, x  = change_in_stock, fill = region)) +
  geom_violin(alpha = 0.7) +
  geom_point() +
  theme_light() +
  guides(fill = "none") +
  labs(y = "", x = "% change in seafood stocks") +
  scale_fill_manual(values = artis_palette(6)) +
  facet_wrap(~ scenario))

# Define a consistent color mapping for all species
species_colors <- c(
  "engraulis anchoita" = "#6A3D9A", 
  "engraulis encrasicolus" = "#E31A1C", 
  "engraulis japonicus" = "#FF7F00", 
  "engraulis ringens" = "#FDBF6F", 
  "gadus macrocephalus" = "#CAB2D6", 
  "katsuwonus pelamis" = "#33A02C", 
  "thunnus albacares" = "#1F78B4"
)

species_colors <- c(
  "engraulis anchoita" = "#642233", 
  "engraulis encrasicolus" = "#8c3d37", 
  "engraulis japonicus" = "#ab663f", 
  "engraulis ringens" = "#c29550", 
  "gadus macrocephalus" = "#c8b366", 
  "katsuwonus pelamis" = "#93a988", 
  "thunnus albacares" = "#5d888b"
)

# Seafood products with increasing trends in catch
(safer_prospective_products_graph <- safer_prospective_products %>%
  ggplot(aes(x = n, y = region, fill = sciname_hs_modified)) +
  geom_col(position = "fill") +
  theme_light() +
  scale_fill_manual(values = species_colors) +  # Use the shared color mapping
  labs(x = "Prop of countries in a region", y = "", fill = "Scientific name") +
  facet_wrap(~ scenario) +
  theme(axis.text.x= element_text(size = 8)))

# Seafood products with decreasing trends in catch
(unsafe_prospective_products_graph <- unsafe_prospective_products %>%
  ggplot(aes(x = n, y = region, fill = sciname_hs_modified)) +
  geom_col(position = "fill") +
  theme_light() +
  scale_fill_manual(values = species_colors) +  # Use the shared color mapping
  labs(x = "Prop of countries in a region", y = "", fill = "Scientific name") +
  facet_wrap(~ scenario)  +
  theme(axis.text.x= element_text(size = 8)))

# Mean foreign dependency, by region, by year
consumer_foreign_dependencies %>%
  group_by(region, year) %>%
  summarize(foreign_dependency = mean(foreign_dependency)) %>%
  filter(!is.na(region)) %>%
  ggplot(aes(x = year, y = foreign_dependency, color = region)) +
  geom_point() +
  scale_color_manual(values = artis_palette(6)) + 
  scale_fill_manual(values = artis_palette(6)) +
  geom_smooth(aes(fill = region), method = "gam", alpha = 0.2) +
  theme_light() +
  labs(x = "", y = "% foreign dependency", color = "Region") +
  guides(fill = "none") +
  theme(legend.position="bottom")

# Case study looking at foreign dependency by country
consumer_foreign_dependencies %>%
  filter(consumer_iso3c == "KEN") %>%
  ggplot(aes(x = year, y = foreign_dependency)) +
  geom_point()+
  geom_smooth(method = "gam", alpha = 0.2) +
  theme_light() +
  labs(x = "", y = "% foreign dependency") +
  guides(fill = "none") +
  theme(legend.position="bottom")

# Boxplot time series of foreign dependency by region
foreign_dependency_time_series <- consumer_foreign_dependencies %>%
  filter(!is.na(region)) %>%
  ggplot(aes(x = factor(year), y = foreign_dependency, fill = region)) +  # Convert year to factor to treat as categorical
  geom_boxplot() +  # Create separate plots for each region
  scale_fill_manual(values = artis_palette(6)) +  # Apply custom color palette
  theme_light() +
  labs(x = "", y = "Foreign Dependency", fill = "Region") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill = "none")

# look at time series data for 
consumer_foreign_dependencies %>%
  filter(consumer_iso3c == "VCT") %>%
  mutate(foreign_dependency = 100 * foreign_dependency) %>%
  ggplot(aes(x = year, y = foreign_dependency)) +
  geom_point() +
  geom_line() +
  theme_minimal_hgrid() +
  labs(x = "", y = "% foreign dependency")
  
# Look at data coverage for adaptive capacity
world_map <- ne_countries(scale = "medium", returnclass = "sf")

world_map <- world_map %>%
  left_join(ac_coverage, by = c("iso_a3" = "consumer_iso3c"))
  
  world_map %>%
ggplot() +
  geom_sf(data = ocean, fill = "#8080ff80") +
  geom_sf(aes(fill = factor(artis)), color = "black") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  coord_sf(crs = "+proj=robin") +
  labs(fill = "# AC datasets ARTIS\nconsuming country\nis missing from") +
    scale_fill_brewer(palette = "Reds", na.value = "gray")
  
  
# ANOVA testing prop at least species vs region
leveneTest(prop_at_least_species ~ region, data = con_joined)
aov(prop_at_least_species ~ region, data = con_joined) %>% summary()
TukeyHSD(aov(prop_at_least_species ~ region, data = con_joined))

# ... genus ...
leveneTest(prop_at_least_genus ~ region, data = con_joined)
aov(prop_at_least_genus ~ region, data = con_joined) %>% summary()
TukeyHSD(aov(prop_at_least_genus ~ region, data = con_joined))

# ... family ...
leveneTest(prop_at_least_family ~ region, data = con_joined)
aov(prop_at_least_family ~ region, data = con_joined) %>% summary()

# ... order ...
leveneTest(prop_at_least_order ~ region, data = con_joined)
aov(prop_at_least_order ~ region, data = con_joined) %>% summary()

# Correlations between variables (plots + pearson)
pairs(con_na_removed[c(3:6)])
cor(con_na_removed[c(3:6)])

# Linear model between weight
weight_shannon_lm <- lm(shannon ~ log(total_weight) + region * log(total_weight), data = con_joined)
summary(weight_shannon_lm)

# Test to see if adding unlinked fb/slb data significantly changes countries' distributions in proportion of reported absences - it is significant! p = 0.04.
t.test(linked_unlinked_props$prop_missing, linked_props$prop_missing, alternative = "less")

# Testing out normalizing data - potentially might need to regularize if data is not normally distrubted.
hist((log(con_na_removed$total_weight) - min(log(con_na_removed$total_weight))) / (max(log(con_na_removed$total_weight)) - min(log(con_na_removed$total_weight))))
countrycode(con_joined$consumer_iso3c, "iso3c", "region")
```

> Takeaways: Little correlation between hdi and total weight + shannon diversity, but stronger, positive correlation between weight and shannon diversity (as seen in correlatnion + scatter plots)


```{r visualize sensitivity data}
# Visualziation for importance on supply
supply_importance %>%
  filter(year == 2019) %>%
  mutate(importance_on_protein_cons = importance_on_protein_cons * 100) %>%
  ggplot(aes(x = region, y = importance_on_protein_cons, fill = region)) +
  geom_violin(alpha = 0.5) +
  geom_point() +
  theme_minimal_hgrid() +
  scale_fill_manual(values = artis_palette(6)) +
  guides(fill = "none") +
  labs(y = "% importance of marine capture taxa\non overall protein supply",
       caption = "0 = No importance, 1 = 100% importance on protein supply")

# Time series of importance over time
(supply_importance_ts <- supply_importance %>%
  group_by(year, region) %>%
  mutate(importance_on_protein_cons = importance_on_protein_cons * 100) %>%
  ggplot(aes(x = factor(year), y = importance_on_protein_cons, fill = region)) +
  geom_boxplot() +
  theme_minimal_hgrid() +
  scale_fill_manual(values = artis_palette(6)) +
  labs(color = "Region", y = "% mean importance") +
  scale_x_discrete(breaks = seq(2010, 2019, by = 1)) +
  labs(x = "", y = "% importance of marine capture taxa\non overall protein supply"))

# Look specifically at the USA
artis_fao_fbb %>%
  group_by(year, consumer_iso3c) %>%
  mutate(importance_on_protein_cons = prop_consumption * prop_aquatic_animal) %>%
  filter(!is.na(region)) %>%
  filter(year == 2019,
         consumer_iso3c == "USA") %>%
  ungroup() %>%
  select(prop_consumption,
         prop_aquatic_animal,
         importance_on_protein_cons,
         habitat,
         method,
         -year) %>%
  mutate(prop_consumption = round(prop_consumption, 3),
         prop_aquatic_animal = round(prop_aquatic_animal, 3),
         importance_on_protein_cons = round(importance_on_protein_cons, 3))

# Time series of overall mean proportion of conusmed protein
left_join(aquatic_animal_proteins, total_protein) %>%
  group_by(iso3c, year) %>%
  summarize(prop_aquatic_animal = a_a_protein / t_p) %>%
  group_by(year) %>%
  summarize(overall_prop = mean(prop_aquatic_animal, na.rm = TRUE)) %>%
  ggplot(aes(x = as.numeric(year), y = overall_prop)) +
  geom_line() +
  geom_point() +
  labs(x = "Year") +
  theme_minimal_hgrid() +
  labs(y = "Seafood as a proportion of\ntotal consumed protein, globally") +
   scale_x_continuous(breaks=seq(2010,2019,1))
```

```{r visualize exposure data}
# Safer products
safer_prospective_products <- consumption_future %>% 
  filter(consumer_iso3c != producer_iso3c,
         !is.na(live_weight_t),
         !is.na(future_change_catch)) %>%
  mutate(future_change_catch = case_when(
    future_change_catch > 0 ~ (future_change_catch / 100) + 1,
    future_change_catch < 0 ~ 1 - ((future_change_catch / 100) * -1), # Convert percentage to proportion
    future_change_catch == 0 ~ 1)) %>%
  group_by(consumer_iso3c, scenario, sciname_hs_modified) %>%
  mutate(future_weight_t = live_weight_t * future_change_catch,
            change_in_stock = (future_weight_t / live_weight_t)) %>%
  group_by(consumer_iso3c, scenario) %>%
  mutate(total_present_weight = sum(live_weight_t)) %>%
  ungroup() %>%
  mutate(change_in_stock = case_when(
    change_in_stock > 1 ~ (change_in_stock - 1) * 100,
    change_in_stock < 1 ~ (1 - change_in_stock) * -100,
    change_in_stock == 1 ~ 0
  )) %>%
  group_by(consumer_iso3c, scenario, sciname_hs_modified) %>%
  mutate(pct_influence = live_weight_t / total_present_weight,
         change_in_stock = pct_influence * change_in_stock) %>% # weight stock changes by % live weight for a conusmer has with respect to their total weight (so not all changes in stocks are treated equally (i.e. one change in stock has a high percent, but a very low recorded weight))
  group_by(consumer_iso3c, scenario) %>%
  slice_max(change_in_stock, n = 1) %>%
  exploreARTIS::add_region("consumer_iso3c", region.col.name = "region") %>%
  group_by(region, scenario) %>%
  count(sciname_hs_modified) %>%
  filter(!is.na(region))

# Less safe products
unsafe_prospective_products <- consumption_future %>% 
  filter(consumer_iso3c != producer_iso3c,
         !is.na(live_weight_t),
         !is.na(future_change_catch)) %>%
  mutate(future_change_catch = case_when(
    future_change_catch > 0 ~ (future_change_catch / 100) + 1,
    future_change_catch < 0 ~ 1 - ((future_change_catch / 100) * -1), # Convert percentage to proportion
    future_change_catch == 0 ~ 1)) %>%
  group_by(consumer_iso3c, scenario, sciname_hs_modified) %>%
  mutate(future_weight_t = live_weight_t * future_change_catch,
            change_in_stock = (future_weight_t / live_weight_t)) %>%
  group_by(consumer_iso3c, scenario) %>%
  mutate(total_present_weight = sum(live_weight_t)) %>%
  ungroup() %>%
  mutate(change_in_stock = case_when(
    change_in_stock > 1 ~ (change_in_stock - 1) * 100,
    change_in_stock < 1 ~ (1 - change_in_stock) * -100,
    change_in_stock == 1 ~ 0
  )) %>%
  group_by(consumer_iso3c, scenario, sciname_hs_modified) %>%
  mutate(pct_influence = live_weight_t / total_present_weight,
         change_in_stock = pct_influence * change_in_stock) %>% # weight stock changes by % live weight for a conusmer has with respect to their total weight (so not all changes in stocks are treated equally (i.e. one change in stock has a high percent, but a very low recorded weight))
  group_by(consumer_iso3c, scenario) %>%
  slice_min(change_in_stock, n = 1) %>%
  exploreARTIS::add_region("consumer_iso3c", region.col.name = "region") %>%
  group_by(region, scenario) %>%
  count(sciname_hs_modified) %>%
  filter(!is.na(region))






theme_fancy_map <- function() {
  theme_void(base_family = "IBM Plex Sans") +
    theme(
      plot.title = element_text(face = "bold", hjust = 0.13, size = rel(1.4)),
      plot.subtitle = element_text(hjust = 0.13, size = rel(1.1)),
      plot.caption = element_text(hjust = 0.13, size = rel(0.8), color = "grey50"),
    )
}


world_map <- ne_countries(scale = "medium", returnclass = "sf")

world_map <- world_map %>%
  left_join(consumer_stock_change[consumer_stock_change$scenario == "2030ssp126",], by = c("iso_a3" = "consumer_iso3c"))
  
  world_map %>%
ggplot() +
  geom_sf(data = ocean, fill = "#8080ff80") +
  geom_sf(aes(fill = change_in_stock), color = "black") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  coord_sf(crs = "+proj=robin") +
    scale_fill_stepsn(
    colours = scales::brewer_pal(palette = "YlGnBu")(9),
    breaks = seq(-20, 140, by = 20)
  )
  
  
  
consumer_stock_change  %>%
  ggplot(aes(x = change_in_stock)) +
  # Fill each histogram bar using the x axis category that ggplot creates
  geom_histogram(
    aes(fill = after_stat(factor(x))), 
    binwidth = 15, boundary = 0, color = "white"
  ) +
  # Fill with the same palette as the map
  scale_fill_brewer(palette = "YlGnBu", guide = "none") +
  # Modify the x-axis labels to use >9%
  scale_x_continuous(
    breaks = seq(-20, 140, by = 20), # Adjust to have breaks at equal intervals
    labels = case_match(
      seq(-20, 140, by = 20),
      2 ~ "2%",
      10 ~ ">9%",
      .default = as.character(seq(-20, 140, by = 20))
    )
  ) +
  theme_void() +
  theme(
    axis.text.x = element_text(size = rel(0.55)),
    axis.title.x = element_text(size = rel(0.68), margin = margin(t = 3, b = 3), face = "bold")
  )



consumer_stock_change %>%
  ggplot(aes(x = pct_change, fill = scenario)) +
  geom_histogram(alpha = 0.5, position = "identity", color = "black", boundary = 0) +
  theme_cowplot() +
  labs(x = "% Change in stock\n(future from present)", y = "# Countries", fill = "Scenario")

consumer_stock_change %>%
  exploreARTIS::add_region(col = "consumer_iso3c", region.col.name = "region") %>%
  filter(!is.na(region)) %>%
  ggplot(aes(y = region, x = pct_change, fill = region)) +
  geom_violin(alpha = 0.5) +
  geom_point() +
  theme_cowplot(10) +
  facet_wrap(~ scenario) +
  scale_fill_manual(values = artis_palette(6)) +
  labs(x = "% Change in stock\n(future from present)", y = "") +
  guides(fill = "none") +
  theme_light()

consumer_stock_change_pre %>%
  mutate(pct_change = 100 * ((change_in_stock - live_weight_t) / live_weight_t)) %>%
  ggplot(aes(x = pct_change, fill = scenario)) +
  geom_histogram(color = "black", boundary = 0) +
  xlim(-100, 100) +
  facet_wrap(~ scenario) +
  theme_cowplot() +
  labs(x = "% Change Catch", y = "Count") +
  guides(fill = "none")

df %>%
  pivot_longer(cols = c("ssp126", "ssp585")) %>%
  ggplot(aes(x = value, fill = name)) +
  geom_histogram(color = "black", boundary = 0) +
  theme_cowplot() +
  xlim(-100, 100) +
  facet_wrap(~ name) +
  labs(x = "% Change Catch", y = "Count") +
  guides(fill = "none")
```


## Save Images

```{r Save images}
# Save images
ggsave("../images/country_weights.jpg", plot = country_weights, device = "jpeg", height = 3, width = 5, units = "in")

ggsave("../images/country_diversities.jpg", plot = country_diversities, device = "jpeg", height = 3, width = 5, units = "in")

ggsave("../images/shannon_versus_weight.jpg", plot = shannon_versus_weight, device = "jpeg", height = 3, width = 5, units = "in")

ggsave("../images/prop_versus_tax_versus_country.jpg", plot = prop_versus_tax_versus_country, device = "jpeg", height = 4, width = 9, units = "in")

ggsave("../images/prop_absences_linked.jpg", plot = prop_absences_linked, device = "jpeg", height = 3, width = 5, units = "in")

ggsave("../images/prop_absences_linked_unlinked.jpg", plot = prop_absences_linked_unlinked, device = "jpeg", height = 3, width = 5, units = "in")

ggsave("../images/prop_map_linked.png", plot = prop_map_linked, device = "jpeg", width = 6, height = 4)

ggsave("../images/prop_map_linked_unlinked.png", plot = prop_map_linked_unlinked, device = "jpeg", width = 6, height = 4)

ggsave("../images/consumer_stock_change_graph.png", plot = consumer_stock_change_graph, device = "jpeg", width = 10, height = 6)

ggsave("../images/safer_prospective_products_graph.png", plot = safer_prospective_products_graph, device = "jpeg", width = 9, height = 5)

ggsave("../images/unsafe_prospective_products_graph.png", plot = unsafe_prospective_products_graph, device = "jpeg", width = 9, height = 5)

ggsave("../images/foreign_dependency_time_series.jpg", plot = foreign_dependency_time_series, device = "jpeg", width = 20, height = 2)

ggsave("../images/supply_importance_ts.jpg", plot = supply_importance_ts, device = "jpeg", width = 9, height = 5)
```
