---
title: "Seafood Analysis"
author: "Connor Quiroz"
date: "2024-11-15"
output: html_document
---

# Setup / Load in Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# General data cleaning + visualization + analysis packages
library(tidyverse)
library(ggformula)
library(countrycode)
library(data.table)
library(arrow)

# Map creation
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)

# For identifying higher taxa levels
library("taxa")

# Load in packages needed for ARTIS
library(devtools)
library(tidytext)
devtools::install_github("davidsjoberg/ggsankey")
library(ggsankey)
devtools::install_github("Seafood-Globalization-Lab/exploreARTIS@v1.0.0", dependencies = TRUE)
library(exploreARTIS)

# For Packages for fishbase
remotes::install_github("cboettig/duckdbfs", force = TRUE)
remotes::install_github("ropensci/rfishbase")
library(duckdbfs)
library(rfishbase)
```

```{r initialize functions}
at_least_vars <- function(data) {
  if (any(names(data) %in% "producer_iso3c")) {
    data %>%
      group_by(producer_iso3c, sciname) %>%
      mutate(
        at_least_genus = case_when(taxa_level == "species" |
                                     taxa_level == "genus" ~ 1, TRUE ~ 0),
        at_least_family = case_when(
          taxa_level == "species" |
            taxa_level == "genus" | taxa_level == "family" ~ 1,
          TRUE ~ 0
        ),
        at_least_order = case_when(
          taxa_level == "species" |
            taxa_level == "genus" |
            taxa_level == "family" | taxa_level == "order" ~ 1,
          TRUE ~ 0
        ),
        at_least_class = case_when(
          taxa_level == "species" |
            taxa_level == "genus" |
            taxa_level == "family" |
            taxa_level == "order" | taxa_level == "class" ~ 1,
          TRUE ~ 0
        )
      )
  }
  else {
    data %>%
      group_by(sciname) %>%
      mutate(
        at_least_genus = case_when(taxa_level == "species" |
                                     taxa_level == "genus" ~ 1, TRUE ~ 0),
        at_least_family = case_when(
          taxa_level == "species" |
            taxa_level == "genus" | taxa_level == "family" ~ 1,
          TRUE ~ 0
        ),
        at_least_order = case_when(
          taxa_level == "species" |
            taxa_level == "genus" |
            taxa_level == "family" | taxa_level == "order" ~ 1,
          TRUE ~ 0
        ),
        at_least_class = case_when(
          taxa_level == "species" |
            taxa_level == "genus" |
            taxa_level == "family" |
            taxa_level == "order" | taxa_level == "class" ~ 1,
          TRUE ~ 0
        )
      )
  }
}



taxa_level_vars <- function(data, ungroup = FALSE) {
  if (ungroup == FALSE) {
    data %>%
      mutate(
        taxa_level = case_when(
          sciname == kingdom ~ "kingdom",
          sciname == phylum ~ "phylum",
          sciname == superclass ~ "superclass",
          sciname == class ~ "class",
          sciname == order ~ "order",
          sciname == family ~ "family",
          sciname == subfamily ~ "subfamily",
          sciname == genus ~ "genus",
          str_detect(sciname, pattern = "\ ") ~ "species"
        )
      )
  }
  
  else {
    data %>%
      ungroup() %>%
      distinct(sciname) %>%
      left_join(sciname, by = "sciname") %>%
      mutate(
        taxa_level = case_when(
          sciname == kingdom ~ "kingdom",
          sciname == phylum ~ "phylum",
          sciname == superclass ~ "superclass",
          sciname == class ~ "class",
          sciname == order ~ "order",
          sciname == family ~ "family",
          sciname == subfamily ~ "subfamily",
          sciname == genus ~ "genus",
          str_detect(sciname, pattern = "\ ") ~ "species"
        )
      )
  }
  
  
}

# METHOD 1: FAOAREAS
taxa_presence_or_absence_faoareas <- function(data = "fishbase", obtain_stats = FALSE) {
  # Determine whether to use FB or SLB data
  if (data == "fishbase") {
    artis_fishbase_locations <- fb_presences_faoareas
    species_codes <- fb_species_codes
  }
  else {
    artis_fishbase_locations <- slb_presences_faoareas
    species_codes <- slb_species_codes
  }
  
  # Join species codes to species / genus names
  artis_fishbase_locations <- left_join(artis_fishbase_locations, species_codes[, c("SpecCode", "Genus", "Species")], by = "SpecCode")
  # Identify what eez species distrubutions are in (with faoareas)
  eez_assignments <- data.frame(eez_name = 1:nrow(artis_fishbase_locations))
  
  # Initialize list
  country_list <- list()
  
  # Set length of list
  length(country_list) <- nrow(artis_fishbase_locations)
  
  # METHOD 1: rfishbase::faoareas()
  
  # Assign a country into the present countries if a species distribution intersects with a country's EEZ
  for (i in 1:nrow(artis_fishbase_locations)) {
    for (j in 1:nrow(eez_extents)) {
      lat_check <- (abs(artis_fishbase_locations$SouthernLatitude[i]) <= abs(eez_extents$y_max[j])) &
        (abs(artis_fishbase_locations$NorthernLatitude[i]) >= abs(eez_extents$y_min[j]))
      
      long_check <- (abs(artis_fishbase_locations$WesternLongitude[i]) <= abs(eez_extents$x_max[j])) &
        (abs(artis_fishbase_locations$EasternLongitude[i]) >= abs(eez_extents$x_min[j]))
      if (lat_check & long_check) {
        country_list[[i]] <- c(country_list[[i]], eez_extents$ISO_TER1[j])
        
      }
      if (j == nrow(eez_extents)) {
        if (is.null(country_list[[i]])) {
          country_list[[i]] <- NA
          eez_assignments$eez_name[i] = country_list[[i]]
        }
        else {
          eez_assignments$eez_name[i] = paste0(c(country_list[[i]]), collapse = " ")
        }
      }
    }
  }
  
  # Number of unique country combinations
  length(unique(eez_assignments$eez_name))
  
  # Number of N/S/E/W combinations (make sure it roughly matches with number of unique combinations.)
  artis_fishbase_locations %>%
    distinct(
      NorthernLatitude,
      SouthernLatitude,
      EasternLongitude,
      EasternLongitude,
      WesternLongitude
    )
  
  # Country coverage using FAO distribution data: 154 countries (less than when using country() data.
  length(unique(unlist(country_list)))
  
  # Combine fishbase fishbase location data with their respective countries they're found in
  artis_fishbase_locations_faoareas <- cbind(artis_fishbase_locations, eez_assignments)
  
  # Number of species covered in fishbase via faoareas() - 782 species
  length(unique(artis_fishbase_locations_faoareas[!is.na(artis_fishbase_locations_faoareas$eez_name), ]$Species))
  
  artis_fishbase_locations_faoareas <- artis_fishbase_locations_faoareas %>%
    select(eez_name, Species) %>%
    rename(sciname_joinable_to_fishbase = "Species",
           countries_found = "eez_name")
  
  artis_fishbase_locations_faoareas <- artis_fishbase_locations_faoareas %>%
    distinct(sciname_joinable_to_fishbase, .keep_all = TRUE) %>%
    mutate(source = data)
  
  
  consumption_countries_joined_faoareas <- left_join(consumption_sciname,
                                                     artis_fishbase_locations_faoareas,
                                                     by = "sciname_joinable_to_fishbase")
  #
  # Determine whether a species is present or absent in an EEZ
  consumption_countries_joined_faoareas <- consumption_countries_joined_faoareas %>%
    ungroup() %>%
    mutate(presence_or_absence = case_when(
      str_detect(countries_found, eez_iso3c) ~ 1,
      !str_detect(countries_found, eez_iso3c) ~ 0,
      TRUE ~ NA
    ))
  
  return(consumption_countries_joined_faoareas)
}

# METHOD 2: rfishbase::country()

# Another way to get species distributions in certain countries (need to see how many countries are represented in this vs FAO, which doesn't directly report countries, but needs to be joined on eez data).
taxa_presence_or_absence <- function(data = "fishbase", obtain_stats = FALSE) {
  
  # Determine whether to use FB or SLB data
  if (data == "fishbase") {
    artis_fishbase_locations <- fb_presences_country
    species_codes <- fb_species_codes
  }
  else {
    artis_fishbase_locations <- slb_presences_country
    species_codes <- slb_species_codes
  }
  
  if (obtain_stats == TRUE) {
    # faoareas() and country() have equal coverage - 1075 species from ARTIS' 1326 species
    # 229 countries when dealing with country() data, but how many covered countries when dealing with faoareas() data?
    num_countries <- artis_fishbase_locations %>%
      filter(Status %in% c("native", "Native", "introduced", "endemic") & !is.na(country)) %>%
      mutate(eez_name = countrycode(country, origin = 'country.name', destination = 'iso3c')) %>%
      distinct(eez_name) %>%
      summarize(length = length(eez_name)) %>%
      pull(length)
    print(paste0("Number of countries joined to ", data, ": ", as.character(num_countries)))
    
    # Data coverage:
    num_species_artis <- sum(str_detect(
      unique(scinames_excluding_tradeflows$sciname_joinable_to_fishbase), " "), na.rm = TRUE)
    num_species_fishbase <- artis_fishbase_locations %>%
      summarize(unique_species = length(unique(Species))) %>%
      pull(unique_species)
    
    species_coverage_pct <- round((num_species_fishbase / num_species_artis), 2) * 100
    
    # 81% % coverage of all ARTIS species in fishbase - also try sealifebase?
    print(paste0("Number of species in ", sym(data), ": ", num_species_fishbase))
    print(paste0("Number of species in ARTIS", ": ", num_species_artis))
    print(paste0("Percent of ARTIS species that ", sym(data), " has: ", as.character(species_coverage_pct),"%"))
  }
  else {
    # Which countries species are found in (using country() distribution data)
    fishbase_country_presences <- artis_fishbase_locations %>%
      filter(Status %in% c("native", "Native", "introduced", "endemic")) %>%
      mutate(eez_name = countrycode(country, origin = 'country.name', destination = 'iso3c')) %>%
      group_by(ScientificName) %>%
      summarize(countries_found = paste0(unique(eez_name), collapse = " ")) %>%
      rename(sciname_joinable_to_fishbase = "ScientificName") %>%
      mutate(source = data)
    
    consumption_countries_joined <- left_join(scinames_excluding_tradeflows, fishbase_country_presences, by = "sciname_joinable_to_fishbase")
    
    # # See which entries were successfully joined
    # consumption_countries_joined <- consumption_countries_joined %>%
    #   mutate(
    #     joined = case_when(!is.na(eez_iso3c) & !is.na(countries_found) ~ "both",
    #                        !is.na(eez_iso3c) ~ "only in artis",
    #                        TRUE ~ paste0("only in ", data)),
    #     source = case_when(joined == "both" ~ data,
    #                        joined == paste0("only in ", data) ~ data,
    #                        TRUE ~ NA))

    # Determine whether a species is present or absent in an EEZ
    consumption_countries_joined <- consumption_countries_joined %>%
      ungroup() %>%
      mutate(presence_or_absence = case_when(
        str_detect(countries_found, eez_iso3c) ~ 1, !str_detect(countries_found, eez_iso3c) ~ 0,
        TRUE ~ NA
      ))
    
    return(consumption_countries_joined)
  }
  
  
}


# Ocean polygon
ocean <- st_polygon(list(cbind(c(seq(-180, 179, len = 100), rep(180, 100), 
                        seq(179, -180, len = 100), rep(-180, 100)),
                      c(rep(-90, 100), seq(-89, 89, len = 100),
                        rep(90, 100), seq(89, -90, len = 100))))) |>
  st_sfc(crs = "WGS84") |>
  st_as_sf()

create_map <- function(data, fill = "prop_missing") {
  world_map <- ne_countries(scale = "medium", returnclass = "sf")

world_map <- world_map %>%
  left_join(data, by = c("iso_a3" = "eez_iso3c"))
  
  world_map %>%
ggplot() +
  geom_sf(data = ocean, fill = "#8080ff80") +
  geom_sf(aes(fill = !!sym(fill)), color = "black") + 
  scale_fill_viridis_c(option = "plasma") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  coord_sf(crs = "+proj=robin")
}
```


# Data Cleaning

```{r preprocess future climatedata}
# Get list of files for future projections on EACH species
file_names <- list.files(path = "../data/species/", pattern = "\\.csv", full.names = TRUE)

# Obtain species lookup key (will be used in loop join)
species_names <- fread("../data/dbem_spp_list.csv")

# Read in eez lat long extents (use to identify eez territories by species distribution in fishbase)
eez_extents <- fread("../data/eez_lat_long_extents.csv")

# initiate empty df
df <- data.frame()

for (i in 1:length(file_names)) {
  # Read in i'th species file in loop
  df_i <- fread(file_names[i])
  
  # rename species variable to taxon_key to a join can work
  df_i <- df_i %>%
    rename(taxon_key = "species")
  
  df_i <- left_join(df_i, species_names, by = "taxon_key")
  
  # Select only certain variables for certain years and pivot wider
  df_i <- df_i %>%
    filter(year %in% c(2030, 2050, 2100)) %>%
    mutate(year_ssp = paste0(year, ssp), sciname = str_to_lower(paste(genus, species))) %>%
    select(sciname, eez_name, year_ssp, mean_per_change) %>%
    pivot_wider(names_from = year_ssp, values_from = mean_per_change)
  
  # Combine all species observations into one file
  df <- df %>%
    bind_rows(df_i)
}

# Obtain previous state on dataframe (to get unmatched)
df_preprocessed <- df

# Convert eez variable countries to iso3c codes
for (i in 1:length(df$eez_name)) {
  df$eez_name[i] <- countrycode(df$eez_name[i], origin = 'country.name', destination = 'iso3c')
}

# Rename country variable so it can be joined
df <- df %>%
  rename(eez_iso3c = "eez_name")

# See how many countries were not matches
sum(is.na(df$eez_iso3c))

# Number of countries that properly got matched
length(unique(df$eez_iso3c))

# Unmatched countries via countrycode
unmatched_countries <- unique(df_preprocessed$eez_name[c(which(is.na(df$eez_iso3c)))])

# Only keep rows in preprocessed dataset that are unmatched countries
df_preprocessed <- df_preprocessed %>%
  filter(eez_name %in% unmatched_countries)

df_postprocessed <- df_preprocessed

# Get country names out of parenthesis with string detects
for (i in seq_along(df_preprocessed$eez_name)) {
  
  if (xor(str_detect(df_preprocessed$eez_name[i], "\\("), str_detect(df_preprocessed$eez_name[i], "Yemen"))) {
    split_string <- str_split(df_preprocessed$eez_name[i], "\\(")
    split_string <- str_split(split_string[[1]][2], "\\)")
    df_postprocessed$eez_name[i] <- split_string[[1]][1]
  }
  else if (str_detect(df_preprocessed$eez_name[i], "Yemen")) {
    df_postprocessed$eez_name[i] <- str_split(df_preprocessed$eez_name[i], "\\ \\(")[[1]][1]
  }
  
}

# Convert previously unmatched countries to iso3c
for (i in 1:length(df$eez_name)) {
  df_postprocessed$eez_name[i] <- countrycode(df_postprocessed$eez_name[i], origin = 'country.name', destination = 'iso3c')
}

# Rename country variable so it can be joined
df_postprocessed <- df_postprocessed %>%
  rename(eez_iso3c = "eez_name")

# Add in unmatched countries (now all countries are matched)
df <- rbind(df, df_postprocessed)
```

```{r data cleaning for hdi + consumption data}
# Read in cosnumption data
consumption <- read_parquet("../data/example_consumption_eez_2024_12_06.parquet")
consumption_all_years <- consumption
consumption <- consumption %>%
  filter(year == 2019)

# Get unique taxa names (excluding trade flows)
scinames_excluding_tradeflows <- consumption %>%
  ungroup() %>%
  distinct(eez_iso3c, sciname_hs_modified) %>%
  left_join(sciname, by = c("sciname_hs_modified" = "sciname")) %>%
  rename(sciname = "sciname_hs_modified") %>%
  taxa_level_vars() %>%
  rename(sciname_hs_modified = "sciname") %>%
  filter(!is.na(sciname_hs_modified)) %>%
  ungroup()

# Read in taxonomic data
sciname <- read.csv("../data/sciname.csv")

# Combine consumption and taxonomic data
consumption_sciname <- left_join(consumption, sciname, by = "sciname")

# Create phylogenetic variables
consumption_sciname <- taxa_level_vars(consumption_sciname)

consumption_sciname <- consumption_sciname %>%
  exploreARTIS::add_region("consumer_iso3c", region.col.name = "region")

# Read in  Adaptive Capacity data
hdi <- read.csv("../data/hdi.csv")

hdi <- hdi %>%
  rename(consumer_iso3c = "country") %>%
  select(-date_obtained)

# Convert country names to iso3c codes
for (i in 1:length(hdi$consumer_iso3c)) {
  hdi$consumer_iso3c[i] <- countryname(hdi$consumer_iso3c[i], destination = "iso3c")
}

# Variable names for consumption
names(consumption)

# Looking at total weights per country (aggregating species weight in 2019)
con_weight <- consumption %>%
  filter(consumer_iso3c != producer_iso3c & str_detect(sciname, pattern = "\ ")) %>%
  group_by(consumer_iso3c) %>%
  mutate(live_weight_t = as.numeric(live_weight_t)) %>%
  summarize(total_weight = sum(live_weight_t)) %>%
  arrange(desc(total_weight))

# Shannon diversity of countries' imports
con_shannon <- consumption_sciname %>%
  filter(consumer_iso3c != producer_iso3c & str_detect(sciname, pattern = "\ ")) %>%
  group_by(consumer_iso3c, genus) %>%
  summarize(genus_total = sum(live_weight_t)) %>%
  group_by(consumer_iso3c) %>%
  mutate(genus_total_country = sum(genus_total)) %>%
  ungroup() %>%
  mutate(pi = genus_total / genus_total_country, pi_lnpi = pi * log(pi)) %>%
  group_by(consumer_iso3c) %>%
  summarize(shannon = -sum(pi_lnpi))

# Join quantity and diversity
con_joined <- left_join(con_weight, con_shannon, by = "consumer_iso3c")

# Add in hdi values to joined dataset
con_joined <- left_join(con_joined, hdi, by = "consumer_iso3c")

# Store phylogenetic levels in a vector
levels <- c()
levels <- unique(consumption_sciname$taxa_level)

# Remove superclass (only 1 according to taxa_level variable) and species (different analysis to get prop)
levels <- levels[!(levels %in% c("superclass", "species", "phylum"))]

# Proportions of producing countries reporting to **at least** that taxonomic level (should be cumulative probabilities)
# Set up whether a producing country reported to at least a certain level (1 means it could also go lower (e.g., 1 in class means it could be just class or goes all the way to species))
consumption_sciname <- at_least_vars(consumption_sciname)

for (i in levels) {
  con_actual_group <- consumption_sciname %>%
    group_by(producer_iso3c) %>%
    summarize(!!paste0("prop_at_least_", i) := sum(!!sym(paste0("at_least_",i))) / n()) %>%
    rename(consumer_iso3c = "producer_iso3c")
  
  # Join prop of each phylogenetic group to already joined consumption dataset
  con_joined <-
    left_join(con_joined, con_actual_group, by = "consumer_iso3c")
  
}

# Add back in species
levels <- c("species", "genus", "family", "order", "class")

# Proportions of producing countries reporting to exactly that taxonomic level.
for (i in levels) {
  con_actual_group <- consumption_sciname %>%
    group_by(producer_iso3c) %>%
    summarize(!!paste0("prop_exactly_", i) := sum(taxa_level == i) / n(), .groups = "drop") %>%
    rename(consumer_iso3c = "producer_iso3c")
  
  # Join props of each phylogenetic group
  con_joined <- left_join(con_joined, con_actual_group, by = "consumer_iso3c")
  
}

# Percentage of countries that report to species (no species column in sciname data - have to do different way from rest of taxonomic groups)
con_joined <- con_joined %>%
  mutate(prop_at_least_species = prop_exactly_species)

# Update joined dataset to have log transformed total weight as a variable
con_joined <- con_joined %>%
  mutate(log_weight = log(total_weight))

# Add in region (e.g., North America, Asia, etc.)
con_joined <- con_joined %>%
  exploreARTIS::add_region("consumer_iso3c", region.col.name = "region")

# Consumption data without NA's (for correlation plots)
con_na_removed <- con_joined %>%
  drop_na()

# Remove NA region
con_joined <- con_joined %>%
  drop_na(region)

# Sort countries in alphabetical order
con_joined %>%
  arrange(-desc(consumer_iso3c))

# Prints out number of unique values per phylogenetic group
for (i in c(19, 21, 22, 23)) {
  print(c(length(unique(na.omit(consumption_sciname[[i]]))), names(consumption_sciname)[i]))
}

# Join consumption dataset to future climate data
consumption_sciname_future <- left_join(consumption_sciname, df, by = c("eez_iso3c", "sciname"))

length(unique(consumption_sciname$eez_iso3c))
length(unique(df$eez_iso3c))
mask <- unique(consumption_sciname$eez_iso3c) %in% unique(c(df$eez_iso3c))
unique(consumption_sciname$eez_iso3c)[!mask]

length(unique(consumption_sciname$family))
# separate question for whether trade overall increases or homogenizes diets (e.g., need marine capture / aquaculture)
# 503 families in total (all capture + aquaculture)

# Number of orders by country
consumption_sciname %>%
  group_by(eez_iso3c) %>%
  summarize(total_order = length(unique(order)))

consumption %>% ungroup() %>% filter(!str_detect(sciname_hs_modified, " "))
```

```{r add in fishbase / sealifebase data connections}
# Create instances of fishbase/sealifebase data (if they don't already exist)
rmarkdown::render("../code/QuirozConnor_SGL_Obtain_Fishbase_Sealifebase_Data.Rmd")

# Read in fishbase/sealifebase data
fb_presences_country <- read_parquet("../data/fb_slb_data/fb_presences_country.parquet")
slb_presences_country <- read_parquet("../data/fb_slb_data/slb_presences_country.parquet")

fb_presences_faoareas <- read_parquet("../data/fb_slb_data/fb_presences_faoareas.parquet")
slb_presences_faoareas <- read_parquet("../data/fb_slb_data/slb_presences_faoareas.parquet")

fb_species_codes <- read_parquet("../data/fb_slb_data/fb_species_codes")
slb_species_codes <- read_parquet("../data/fb_slb_data/slb_species_codes.parquet")

# Modify sciname casing so that it can be joined to fishbase
scinames_excluding_tradeflows <- scinames_excluding_tradeflows %>%
  mutate(sciname_joinable_to_fishbase = str_to_title(word(sciname_hs_modified, 1)), 
         sciname_joinable_to_fishbase2 = word(sciname_hs_modified, 2), 
         sciname_joinable_to_fishbase = ifelse(
        is.na(sciname_joinable_to_fishbase2),
        sciname_joinable_to_fishbase,
        paste(sciname_joinable_to_fishbase, sciname_joinable_to_fishbase2))) %>%
  select(-sciname_joinable_to_fishbase2) %>%
  relocate(sciname_joinable_to_fishbase, .after = sciname_hs_modified)

# ***
# MAKING SURE ARTIS SCINAMES ALIGN WITH FISHBASE

# # of ARTIS unique ID's (includes higher taxonomic levels that aren't only species) - 1666 total IDs
length(unique(scinames_excluding_tradeflows$sciname_joinable_to_fishbase))

length(!is.na(unique(consumption$sciname_hs_modified)))

# # of ARTIS species (1326 species)
scinames_excluding_tradeflows %>%
  ungroup() %>%
  filter(str_detect(sciname_hs_modified, " ")) %>%
  distinct(sciname_hs_modified) %>%
  pull(sciname_hs_modified) %>%
  length()

# 1326 species with sciname_hs_modified variable
sum(str_detect(unique(na.omit(consumption_sciname$sciname_hs_modified)), " "))

# Unique entries in Fishbase (i.e., # of ARTIS species successfully joined to fishbase - 1382 species)
artis_fishbase_locations <- fb_presences_faoareas

# Total number of joined species succesfully from ARTIS
length(unique(artis_fishbase_locations$Species))
sum(str_detect(unique(artis_fishbase_locations$Species), " "))

# ***


# Get unique taxonomic entries (no repeats)
unique_taxonomy_entries <- scinames_excluding_tradeflows

# Determines whether something is reported to **at least** a given taxonomic level
unique_taxonomy_entries <- at_least_vars(unique_taxonomy_entries)

# Add in species binary Yes or no
unique_taxonomy_entries <- unique_taxonomy_entries %>%
  mutate(at_least_species = case_when(taxa_level == "species" ~ 1, TRUE ~ 0)) %>%
  relocate(at_least_species, .before = at_least_genus)

# Count taxonomic totals
taxa_unreported_props <- data.frame()
taxa_unreported_quantity <- data.frame()
for (i in levels) {
  amount <- unique_taxonomy_entries %>%
    ungroup() %>%
    summarize(sum = sum(!(!!sym(paste0("at_least_",i))))) %>%
    pull(sum)
  total <- length(unique_taxonomy_entries$sciname)
  prop <- amount / total
  taxa_unreported_props <- rbind(taxa_unreported_props, list(i, round(prop, 2)))
  taxa_unreported_quantity <- rbind(taxa_unreported_quantity, list(i, total))
}

# Rename taxa_total variables
taxa_unreported_props <- taxa_unreported_props %>%
  rename(taxa_level = "X.species.", prop = "X0.2")

taxa_unreported_quantity <- taxa_unreported_quantity %>%
  rename(taxa_level = "X.species.", prop = "X2232L")

# Reports proportion and quantities that are not reported to a given taxonomic level.
print(taxa_unreported_props)
print(taxa_unreported_quantity)

# METHOD 1: rfishbase::faoareas() - takes awhile to run thus commented
# fishbase_presences_faoareas <- taxa_presence_or_absence_faoareas(data = "fishbase")
# sealifebase_presences_faoareas <- taxa_presence_or_absence_faoareas(data = "sealifebase")
# 
# # Filter to only have sealifebase data (separate out sealifebase base using source variable)
# only_sealifebase <- sealifebase_presences_faoareas %>%
#   filter(source == "sealifebase")
# 
# # Get indexes where sealifebase found presences or absences
# sealifebase_presence_absences_indexes <- which(sealifebase_presences_faoareas$presence_or_absence %in% c(0,1))
# 
# # Select fishbase + unlinked NA data (excludes sealifebase)
# fishbase_minus_sealifebase <- fishbase_presences_faoareas[-sealifebase_presence_absences_indexes,]
# 
# # Merce fishbase / sealifebase presence data - this will be the data that we use to interpolate higher taxonomic resolutions!
# merged_presence_absence_data_faoareas <- rbind(fishbase_minus_sealifebase, only_sealifebase)
# 
# merged_presence_absence_data_faoareas %>%
#   count(presence_or_absence)


# METHOD 2: rfishbase::conutry()

# Obtain stats on fishbase/sealifebase data
taxa_presence_or_absence(data = "fishbase", obtain_stats = TRUE)
taxa_presence_or_absence(data = "sealifebase", obtain_stats = TRUE)

# Create presence/absence data
fishbase_presences_country <- taxa_presence_or_absence(data = "fishbase")
sealifebase_presences_country <- taxa_presence_or_absence(data = "sealifebase")

# Number of rows in ARTIS data (fishbase + sealifebase presence data)
nrow(fishbase_presences_country)
nrow(sealifebase_presences_country)


fishbase_presences_country %>%
  filter(presence_or_absence %in% c(0,1))

# Check to see if fishbase and sealifebase have any overlapping species (they do not!)
any(sealifebase_presences_country$Species %in% artis_fishbase_locations$Species)

# Combine fishbase/sealifebase data
merged_presence_absence_data_country <- bind_rows(fishbase_presences_country[-which(sealifebase_presences_country$source == "sealifebase"),], sealifebase_presences_country %>% filter(source == "sealifebase"))

merged_presence_absence_data_country <- merged_presence_absence_data_country %>%
  mutate(species = case_when(str_detect(sciname_hs_modified, " ") ~ sapply(str_split(sciname_hs_modified, " "), `[`, 2),
                             TRUE ~ NA))



# Determine if lower resolution taxa are in an eez (e.g., if a species for a given country is found there that is also a lower resolution taxa like actinoptergyii, then all actinoptergyii or higher will be found in that country) -

# List of ARTIS species that aren't matched to either fishbase or sealifebase
unmatched_species <- anti_join(scinames_excluding_tradeflows %>% ungroup() %>% filter(str_detect(sciname_joinable_to_fishbase, " ")) %>% group_by(sciname_joinable_to_fishbase) %>% distinct(sciname_joinable_to_fishbase), bind_rows(fb_presences_country, slb_presences_country), by = c("sciname_joinable_to_fishbase" = "ScientificName")) %>%
  distinct(sciname_joinable_to_fishbase) %>%
  pull(sciname_joinable_to_fishbase)
  
pa_only_artis <- merged_presence_absence_data_country %>%
  mutate(presence_or_absence = case_when(sciname_joinable_to_fishbase %in% unmatched_species ~ NA, TRUE ~ presence_or_absence))

presence_absence_data_country_all_taxa <- data.frame()
for (i in unique(pa_only_artis$eez_iso3c)) {
  # Group data by eez country
  sliced_data <- pa_only_artis %>%
  filter(eez_iso3c == sym(i))

  # Create updated presence on sliced data
  sliced_data_for_merging <- sliced_data %>%
  mutate(unique_vals = str_replace_all(paste0(filter(., presence_or_absence == 1) %>% select(sciname_hs_modified, species, genus, subfamily, family, order, class, superclass, phylum, kingdom) %>%
  unlist() %>%
  unique(), collapse = " "), "[A-Z]", ""), presence_or_absence_all_taxa = case_when(sciname_hs_modified %in%
                                                                                    unmatched_species ~ NA, presence_or_absence == 1 ~ 1,
                                                                                    str_detect(unique_vals, sciname_hs_modified) ~ 1,
                                                                                    TRUE ~ 0))

  # Combine rows of each country
  presence_absence_data_country_all_taxa <- bind_rows(presence_absence_data_country_all_taxa, sliced_data_for_merging)

}

# Count Number of presences/absences in filled in presence data
presence_absence_data_country_all_taxa <- presence_absence_data_country_all_taxa %>%
  relocate(presence_or_absence_all_taxa, .after = presence_or_absence)

# Count number of total presences / absences across ALL taxa levels
presence_absence_data_country_all_taxa %>%
  count(presence_or_absence_all_taxa)

# See which countries are absent
linked_props <- presence_absence_data_country_all_taxa %>%
  group_by(eez_iso3c) %>%
  distinct(sciname_hs_modified, .keep_all = TRUE) %>%
  select(sciname_hs_modified, presence_or_absence_all_taxa) %>%
  count(presence_or_absence_all_taxa) %>%
  mutate(presence_or_absence_all_taxa = as.character(presence_or_absence_all_taxa)) %>%
  pivot_wider(values_from = n, names_from = presence_or_absence_all_taxa, names_glue = "quantity_{presence_or_absence_all_taxa}") %>%
  mutate(prop_missing =  quantity_0 / (quantity_0 + quantity_1))

presence_absence_data_country_all_taxa %>%
  group_by(eez_iso3c) %>%
  distinct(sciname_hs_modified, .keep_all = TRUE) %>%
  select(sciname_hs_modified, presence_or_absence_all_taxa) %>%
  count(presence_or_absence_all_taxa) %>%
  mutate(presence_or_absence_all_taxa = as.character(presence_or_absence_all_taxa)) %>%
  pivot_wider(values_from = n, names_from = presence_or_absence_all_taxa, names_glue = "quantity_{presence_or_absence_all_taxa}") %>%
  mutate(prop_missing =  quantity_0 / (quantity_0 + quantity_1)) %>%
  filter(is.na(prop_missing) & is.na(quantity_1)) %>%
  rename(number_absences = "quantity_0", number_presences = "quantity_1")

# Get species that aren't apart of artis, but are only included in fishbase/sealife base (extra species locations we need to )
pa_excluding_artis <- merged_presence_absence_data_country %>%
  filter(str_detect(sciname_joinable_to_fishbase, " ") & !(joined %in% c("only in artis", "both")))

# See which species aren't matched
# 44 species that aren't mathed to either fishbase or sealifebase
pa_only_artis %>%
  filter(str_detect(sciname_joinable_to_fishbase, " ") & is.na(presence_or_absence)) %>%
  distinct(sciname_joinable_to_fishbase)

# Sum: 93447 - remove species from ARTIS that aren't in fishbase/sealifebase
sum(pa_excluding_artis %>%
  distinct(sciname_joinable_to_fishbase) %>%
  summarize(n = n()) %>%
  pull(n),

pa_only_artis %>%
  filter(str_detect(sciname_joinable_to_fishbase, " ") & !is.na(presence_or_absence)) %>%
  distinct(sciname_joinable_to_fishbase) %>%
  drop_na() %>%
  summarize(n = n()) %>%
  pull(n))

# Sum: 93447
sum(fb_presences_country %>%
      filter(Status %in% c("native", "Native", "introduced", "endemic") & !is.na(country)) %>%
  distinct(Species) %>%
    drop_na() %>%
  summarize(n = n()) %>%
  pull(n),

slb_presences_country %>%
  filter(Status %in% c("native", "Native", "introduced", "endemic") & !is.na(country)) %>%
  distinct(Species) %>%
  drop_na() %>%
  summarize(n = n()) %>%
  pull(n))

# Determine different commercial usages (need to only include commercial fishes for our analysis)
fb_presences_country %>%
  distinct(Importance)

# Get only non-artis species that are of commercial interest
fb_slb_commercial_interests <-  anti_join(bind_rows(fb_presences_country %>% mutate(source = "fishbase"), slb_presences_country %>% mutate(source = "sealifebase")), scinames_excluding_tradeflows %>% ungroup() %>% filter(str_detect(sciname_joinable_to_fishbase, " ")) %>% group_by(sciname_joinable_to_fishbase) %>% distinct(sciname_joinable_to_fishbase), by = c("ScientificName" = "sciname_joinable_to_fishbase")) %>%
  filter((Status %in% c("native", "Native", "introduced", "endemic") & !is.na(country)) & (Importance %in% c("minor commercial", "highly commercial", "commercial", "subsistence fisheries", "of potential interest"))) 

# Convert fb/slb commercial marine country names to iso3c codes + filter out countries NOT in ARTIS
fb_slb_commercial_interests <- fb_slb_commercial_interests %>%
  select(country, ScientificName, Species, Genus, SubFamily, Family, Order, Class, SuperClass, Phylum, Kingdom) %>%
    mutate(country = countrycode(country, origin = 'country.name', destination = 'iso3c')) %>%
    filter(country %in% unique(pa_only_artis$eez_iso3c)) %>%
    group_by(ScientificName) %>%
  mutate(countries_found = paste0(country, collapse = " ")) %>%
  distinct(ScientificName, .keep_all = TRUE) %>%
  mutate(ScientificName = str_to_lower(ScientificName), Species = str_to_lower(Species), Genus = str_to_lower(Genus), SubFamily = str_to_lower(SubFamily), Family = str_to_lower(Family), Order = str_to_lower(Order), Class = str_to_lower(Class), SuperClass = str_to_lower(SuperClass), Phylum = str_to_lower(Phylum), Kingdom = str_to_lower(Kingdom), presence_or_absence = 1) %>%
  rename(sciname_hs_modified = "ScientificName", species = "Species", genus = "Genus", subfamily = "SubFamily", family = "Family", order = "Order", class = "Class", superclass = "SuperClass", phylum = "Phylum", kingdom = "Kingdom", eez_iso3c = "country")

# New problem: Only the genus and species names exist, but not family, order, class, and kingdom. We need to add these in
# New script to refer to to obtain Global Biodiversity Information Facility (rgbif) taxa data - refer to "accepted" column to filter for target species that we will be getting higher taxa names for.

# commercial_products is fed through this script (takes awhile hence in other script)
rmarkdown::render("../code/QuirozConnor_SGL_Obtain_gbif_Data.Rmd")
pa_excluding_artis <- read_parquet("../data/rgbif_data/commercial_products.parquet")

# Create NA's for ARTIS species that aren't matched to either fishbase or sealifebase

# Re-determine if lower resolution taxa are present with both ARTIS + non-ARTIS species
only_artis_1 <- merged_presence_absence_data_country

pa_only_artis <- bind_rows(only_artis_1, fb_slb_commercial_interests %>% mutate(source = "unlinked")) %>%
  mutate(presence_or_absence = case_when(sciname_joinable_to_fishbase %in% unmatched_species ~ NA, TRUE ~ presence_or_absence))
presence_absence_data_linked_unlinked <- data.frame()
for (i in unique(pa_only_artis$eez_iso3c)) {
  # Group data by eez country
  sliced_data <- pa_only_artis %>%
  filter(eez_iso3c == i)

  # Create updated presence on sliced data
  sliced_data_for_merging <- sliced_data %>%
  mutate(unique_vals = str_replace_all(paste0(filter(., presence_or_absence == 1) %>% select(sciname_hs_modified, species, genus, subfamily, family, order, class, superclass, phylum, kingdom) %>%
  unlist() %>%
  unique(), collapse = " "), "[A-Z]", ""), presence_or_absence_all_taxa = case_when(str_detect(unique_vals, sciname_hs_modified) ~ 1,
sciname_hs_modified %in% unmatched_species ~ NA,
TRUE ~ 0))

  # Combine rows of each country
  presence_absence_data_linked_unlinked <- bind_rows(presence_absence_data_linked_unlinked, sliced_data_for_merging)

}

# Count Number of presences/absences in filled in presence data
presence_absence_data_linked_unlinked <- presence_absence_data_linked_unlinked %>%
  relocate(presence_or_absence_all_taxa, .after = presence_or_absence)

presence_absence_data_linked_unlinked %>%
  filter(source != "unlinked" | is.na(source)) %>%
  count(presence_or_absence_all_taxa)

fb_presences_country <- fb_presences_country %>%
  relocate(c(Species, TrueSpecies, Genus), .after = SpecCode) %>%
  mutate(source = "fishbase") %>%
  relocate(source, .before = autoctr)

slb_presences_country <- slb_presences_country %>%
  relocate(c(Species, TrueSpecies, Genus), .after = SpecCode) %>%
  mutate(source = "sealifebase") %>%
  relocate(source, .before = autoctr)

# See which countries are absent
linked_unlinked_props <- presence_absence_data_linked_unlinked %>%
  group_by(eez_iso3c) %>%
  distinct(sciname_hs_modified, .keep_all = TRUE) %>%
  select(sciname_hs_modified, presence_or_absence_all_taxa) %>%
  count(presence_or_absence_all_taxa) %>%
  mutate(presence_or_absence_all_taxa = as.character(presence_or_absence_all_taxa)) %>%
  pivot_wider(values_from = n, names_from = presence_or_absence_all_taxa, names_glue = "quantity_{presence_or_absence_all_taxa}") %>%
  mutate(prop_missing =  quantity_0 / (quantity_0 + quantity_1)) %>%
  rename(number_absences = "quantity_0", number_presences = "quantity_1")

linked_unlinked_props %>%
  filter(is.na(prop_missing) & is.na(number_presences))

# Get data over to Jessica
# fb_slb_species_data <- bind_rows(fb_presences_country, slb_presences_country)
# fb_slb_species_data <- fb_slb_species_data %>%
#   rename(Sciname = Species, Species = TrueSpecies)
# str(fb_slb_species_data)
# write_parquet(fb_slb_species_data, "../data/fb_slb_species_data.parquet")
# write_csv(fb_slb_species_data, "../data/fb_slb_species_data.csv")
```

# Data Visualization + Analysis

```{r iterative process for checking diversity across taxonomic levels (e.g., genus, family, etc.)}
for (i in levels) {
  # Shannon diversity of countries' imports
  con_iteration <- consumption_sciname %>%
    filter(year == 2019 &
             consumer_iso3c != producer_iso3c & taxa_level == i) %>%
    group_by(consumer_iso3c, sciname) %>%
    summarize(genus_total = sum(live_weight_t)) %>%
    group_by(consumer_iso3c) %>%
    mutate(genus_total_country = sum(genus_total)) %>%
    ungroup() %>%
    mutate(pi = genus_total / genus_total_country,
           pi_lnpi = pi * log(pi)) %>%
    group_by(consumer_iso3c) %>%
    summarize(shannon_custom = -sum(pi_lnpi))
  
# Create plot
plot_iteration <-
  left_join(con_joined, con_iteration, by = "consumer_iso3c") %>%
  ggplot(aes(x = shannon_custom)) +
  geom_histogram(color = "black") +
  labs(x = paste0("Shannon diversity (", i, ")"), y = "Frequency") +
  theme_light()

boxplot_iteration <-
  left_join(con_joined, con_iteration, by = "consumer_iso3c") %>%
  ggplot(aes(x = region, y = shannon_custom, fill = region)) +
  geom_violin(alpha = 0.5) +
  geom_point() +
  labs(x = "", y = paste0("Shannon diversity (", i, ")")) +
  guides(fill = "none") +
  scale_fill_manual(values = artis_palette(length(unique(con_joined$region)))) +
  theme_light()

# Set median value for median line in graph
col_name_exactly <- sym(paste0("prop_exactly_", i))
median_value_exactly <- con_joined %>%
  summarise(median = median(!!col_name_exactly, na.rm = TRUE)) %>%
  pull(median)

# Set median value for median line in graph
col_name_at_least <- sym(paste0("prop_at_least_", i))
median_value_at_least <- con_joined %>%
  summarise(median = median(!!col_name_at_least, na.rm = TRUE)) %>%
  pull(median)

prop_exactly_taxalevel_versus_hdi <- con_joined %>%
  ggplot(aes(
    x = hdi,
    y = .data[[paste0("prop_exactly_", i)]],
    color = region,
    size = shannon
  )) +
  scale_color_manual(values = artis_palette(length(unique(con_joined$region)))) +
  geom_point() +
  theme_light() +
  labs(color = "",
       x = "Human Development Index",
       y = paste0("Proportion of production\nreported to exactly ", i),
       size = paste0("Shannon diversity (", i, ")")) +
  scale_size(range = c(0, 2)) +
  ylim(0.0, 1.0) +
  geom_abline(aes(intercept = median_value_exactly, slope = 0), linetype = 2, size = 1.1, alpha = 0.5) +
  guides(color = guide_legend(title = paste0("Median proportion\nreported: ", round(median_value_exactly, 2)), title.theme = element_text(face = "bold.italic"), order = 1), size = guide_legend(order = 2))

prop_at_least_taxalevel_versus_weight <- con_joined %>%
  ggplot(aes(x = log(total_weight), y = .data[[paste0("prop_at_least_", i)]], color = region, size = hdi)) +
  scale_color_manual(values = artis_palette(length(unique(con_joined$region)))) +
  geom_point()+
  theme_light() +
  labs(color = "", x = "Log transformed total consumed \nseafood weight (tons)", y = paste0("Proportion of production\nreported to at least ", i), size = "HDI") +
  scale_size(range = c(0,2)) +
  ylim(0.0, 1.0) +
  geom_abline(aes(intercept = median_value_at_least, slope = 0), linetype = 2, size = 1.1, alpha = 0.5) +
  guides(color = guide_legend(title = paste0("Median proportion\nreported: ", round(median_value_at_least, 2)), title.theme = element_text(face = "bold.italic"), order = 1), size = guide_legend(order = 2))

prop_at_least_taxalevel_versus_hdi <- con_joined %>%
  ggplot(aes(
    x = hdi,
    y = .data[[paste0("prop_at_least_", i)]],
    color = region,
    size = shannon
  )) +
  scale_color_manual(values = artis_palette(length(unique(con_joined$region)))) +
  geom_point() +
  theme_light() +
  labs(color = "",
       x = "Human Development Index",
       y = paste0("Proportion of production\nreported to at least ", i),
       size = paste0("Shannon diversity (", i, ")")) +
  scale_size(range = c(0, 2)) +
  ylim(0.0, 1.0) +
  geom_abline(aes(intercept = median_value_at_least, slope = 0), linetype = 2, size = 1.1, alpha = 0.5) +
  guides(color = guide_legend(title = paste0("Median proportion\nreported: ", round(median_value_at_least, 2)), title.theme = element_text(face = "bold.italic"), order = 1), size = guide_legend(order = 2))
  
  # Print plot
  print(plot_iteration)
  print(boxplot_iteration)

  # Shannon sd
  shannon_sd <- left_join(con_joined, con_iteration, by = "consumer_iso3c") %>% pull(shannon_custom) %>% sd()
  # print(paste0(i, " standard deviation: ", signif(shannon_sd, 3)))

  # Shannon max/min
  shannon_max <- con_iteration %>% pull(shannon_custom) %>% max()
  shannon_min <- con_iteration %>% pull(shannon_custom) %>% min()
  print(paste0(i, " shannon [min, max]: [", round(shannon_min, 2), ", ", round(shannon_max, 2), "]"))
  print(con_iteration)
  
  ggsave(paste0("../images/prop_exactly_",i , "_versus_hdi.jpg"), plot = prop_exactly_taxalevel_versus_hdi, device = "jpeg", height = 4, width = 6, units = "in")
  ggsave(paste0("../images/prop_at_least_",i , "_versus_weight.jpg"), plot = prop_at_least_taxalevel_versus_weight, device = "jpeg", height = 4, width = 6, units = "in")
  ggsave(paste0("../images/prop_at_least_",i , "_versus_hdi.jpg"), plot = prop_at_least_taxalevel_versus_hdi, device = "jpeg", height = 4, width = 6, units = "in")
}
```



```{r data visualization + analysis}
# Top 10 total seafood weights by country
(country_weights <- con_joined %>%
  arrange(desc(total_weight)) %>%
  select(consumer_iso3c, total_weight) %>%
  top_n(10) %>%
  ggplot(aes(x = total_weight, 
             y = fct_reorder(consumer_iso3c, desc(-total_weight)))) +
  geom_col() +
  labs(x = "Total seafood weight (tons)", y = "Consuming country (imports)") +
  theme_light())

# Top 10 most diverse seafood by country 
(country_diversities <- con_joined %>%
  arrange(desc(shannon)) %>%
  select(consumer_iso3c, shannon) %>%
  top_n(10) %>%
  ggplot(aes(x = shannon, 
             y = fct_reorder(consumer_iso3c, desc(-shannon)))) +
  geom_col() +
  labs(x = "Shannon Diversity", y = "Consuming country (imports)") +
  theme_light())

# Relationship between shannon diversity and the total weight by country
(shannon_versus_weight <- con_joined %>%
  ggplot(aes(x = log(total_weight), y = shannon, color = hdi)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_color_viridis_c() +
  facet_wrap(~ region) +
  theme_light() +
  labs(x = "Log transformed total seafood weight (tons)", y = "Shannon diversity (species)", color = "HDI"))

# Future climate projections visualization
(ssp_projections <- consumption_sciname_future %>%
  filter(year == 2019 & !is.na(`2100ssp585`)) %>%
  pivot_longer(c(`2030ssp126`, `2030ssp585`, `2050ssp126`, `2050ssp585`,`2100ssp126`, `2100ssp585`),names_to = "ssp", values_to = "percent_change_catch") %>%
  mutate(year = as.numeric(map_chr(str_split(ssp, "ssp"), 1)),
    scenario = map_chr(str_split(ssp, "ssp"), 2)) %>%
  select(region, year, scenario, percent_change_catch) %>%
  group_by(region, year, scenario) %>%
  drop_na() %>%
  summarize(mean_change = mean(percent_change_catch)) %>%
  ggplot(aes(x = year, y = mean_change, color = scenario)) +
  geom_point(size = 1.3) +
  geom_line(size = 1.1) +
  facet_wrap(~ region) +
  scale_color_manual(values = artis_palette(2)) +
  theme_light() +
  labs(x = "Year", color = "SSP", y = "Mean change to annual catch potential\n(Aggregated across countries + species)"))

# Props reported by region by taxonomic resolution
(prop_versus_tax_versus_country <- con_joined %>%
  pivot_longer(cols = c("prop_at_least_species","prop_at_least_genus","prop_at_least_family","prop_at_least_order"), names_to = "level", values_to = "prop") %>%
  mutate(level = str_remove(level, "prop_at_least_"), level = str_to_title(level), level = factor(level, levels = c("Order", "Family", "Genus", "Species"))) %>%
  ggplot(aes(x = reorder(level, -prop), y = prop, fill = region)) +
  geom_boxplot() +
  scale_fill_manual(values = artis_palette(length(unique(con_joined$region)))) +
  theme_light() +
  labs(x = "Taxonomic level", y = "Proportion of production\nreported to at least target\ntaxonomic level", fill = "Region"))

# Proportion of reports that are seen as countrywide absences according to fishbase/sealifebase
(prop_absences <- presence_absence_data_linked_unlinked %>%
  group_by(eez_iso3c) %>%
  distinct(sciname_hs_modified, .keep_all = TRUE) %>%
  select(sciname_hs_modified, presence_or_absence_all_taxa) %>%
  count(presence_or_absence_all_taxa) %>%
  mutate(presence_or_absence_all_taxa = as.character(presence_or_absence_all_taxa)) %>%
  pivot_wider(values_from = n, names_from = presence_or_absence_all_taxa, names_glue = "quantity_{presence_or_absence_all_taxa}") %>%
  mutate(prop_missing =  quantity_0 / (quantity_0 + quantity_1)) %>%
  ggplot(aes(x = prop_missing)) +
  geom_boxplot(fill = artis_palette(1)) +
  labs(x = "Prop of countries' stock reported as absent\n(Fishbase/Sealifebase") +
  theme_light() +
      theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()))

# Create maps
prop_map_linked <- create_map(linked_props) + 
  labs(fill = "Prop of taxa reported as absent")
 
prop_map_unlinked <- create_map(linked_unlinked_props) +
  labs(fill = "Prop of taxa reported as absent")
  
# ANOVA testing prop at least species vs region
leveneTest(prop_at_least_species ~ region, data = con_joined)
aov(prop_at_least_species ~ region, data = con_joined) %>% summary()
TukeyHSD(aov(prop_at_least_species ~ region, data = con_joined))

# ... genus ...
leveneTest(prop_at_least_genus ~ region, data = con_joined)
aov(prop_at_least_genus ~ region, data = con_joined) %>% summary()
TukeyHSD(aov(prop_at_least_genus ~ region, data = con_joined))

# ... family ...
leveneTest(prop_at_least_family ~ region, data = con_joined)
aov(prop_at_least_family ~ region, data = con_joined) %>% summary()

# ... order ...
leveneTest(prop_at_least_order ~ region, data = con_joined)
aov(prop_at_least_order ~ region, data = con_joined) %>% summary()

# Correlations between variables (plots + pearson)
pairs(con_na_removed[c(3:6)])
cor(con_na_removed[c(3:6)])

# Linear model between weight
weight_shannon_lm <- lm(shannon ~ log(total_weight) + region * log(total_weight), data = con_joined)
summary(weight_shannon_lm)

# Testing out normalizing data - potentially might need to regularize if data is not normally distrubted.
hist((log(con_na_removed$total_weight) - min(log(con_na_removed$total_weight))) / (max(log(con_na_removed$total_weight)) - min(log(con_na_removed$total_weight))))
countrycode(con_joined$consumer_iso3c, "iso3c", "region")
```

> Takeaways: Little correlation between hdi and total weight + shannon diversity, but stronger, positive correlation between weight and shannon diversity (as seen in correlatnion + scatter plots)

## Save Images

```{r Save images}
# Save images
ggsave("../images/country_weights.jpg", plot = country_weights, device = "jpeg", height = 3, width = 5, units = "in")

ggsave("../images/country_diversities.jpg", plot = country_diversities, device = "jpeg", height = 3, width = 5, units = "in")

ggsave("../images/shannon_versus_weight.jpg", plot = shannon_versus_weight, device = "jpeg", height = 3, width = 5, units = "in")

ggsave("../images/ssp_projections.jpg", plot = ssp_projections, device = "jpeg", height = 3, width = 6, units = "in")

ggsave("../images/prop_versus_tax_versus_country.jpg", plot = prop_versus_tax_versus_country, device = "jpeg", height = 4, width = 9, units = "in")

ggsave("../images/prop_absences.jpg", plot = prop_absences, device = "jpeg", height = 3, width = 5, units = "in")

ggsave("../images/prop_map_linked.png", plot = prop_map_linked, device = "jpeg", width = 6, height = 4)

ggsave("../images/prop_map_unlinked.png", plot = prop_map_unlinked, device = "jpeg", width = 6, height = 4)
```
